betagouv/seves

- .github/workflows/django.yml
- sv/tests/conftest.py
- sv/tests/test_fichedetection_create.py
- sv/tests/test_fichedetection_form.py
- sv/tests/test_fichedetection_update.py
En lançant `ruff format` dans la CI.
> Vérifier que le format de code est respecté

- core/apps.py
- core/forms.py
- core/templates/core/_dsfr_div.html
Permet de donner le style de DSFR rapidement à un formulaire Django en appliquant un certain nombre de styles par défaut.
> Ajoute un mixin de formulaire DSFR

- sv/static/sv/fichedetection_detail.css
- sv/templates/sv/fichedetection_detail.html
- sv/templates/sv/fichedetection_detail_lieu.html
- sv/templates/sv/fichedetection_detail_prelevement.html
- sv/tests/test_fichedetection_detail.py
Cette PR permet de consulter le détail des lieux et prélèvements d'une fiche détection dans une modale.
> Voir le détail d'un lieu ou d'un prélèvement d'une fiche détection

- conftest.py
- sv/tests/conftest.py
Mise en commun des fixtures qui sont utilisables en dehors de l'app SV.
> Reorganiser les fixtures pytest

- requirements.txt
Cette PR met à jour Django à la version 5.0.8
> MAJ de Django (5.0.8)

- account/apps.py
- account/forms.py
- account/signals.py
- account/static/account/base.css
- account/templates/user_permissions.html
- account/tests/test_handle_permission_view.py
- account/urls.py
- account/views.py
- core/fields.py
- core/forms.py
- core/static/core/base.css
- core/templates/core/base.html
- core/templates/forms/dsfr_toogle.html
- seves/settings.py
- seves/urls.py
Ajout d'une nouvelle app qui contient ce qui est relatif aux comptes des utilisateurs, dont la gestion des droits.
Ajout d'une page qui permet aux personnes dans un certain groupe d'activer les comptes des autres utilisateurs de leur structure.
> Permettre de donner accès a SEVES

- core/static/core/base.css
- core/templates/core/_carte_resume_document.html
- core/templates/core/_fiche_bloc_commun.html
- sv/models.py
- sv/templates/sv/_fichedetection_form__prelevements.html
- sv/templates/sv/fichedetection_detail.html
Suite à la review de design quelques point d'UI et d'UX sont corrigés.
> Corriger quelques points de design

- sv/templates/sv/_fichedetection_form__prelevements_form.html
Corrige le titre de la modale et interdit la saisie d'un prélèvement dans le futur.
#292
> Corriger l'UX dans la modale des prélèvements

- sv/tests/test_fichedetection_performances.py
Pas a jour car plusieurs branches mergées en même temps.
> Corriger les tests de performances

- sv/forms.py
- sv/managers.py
- sv/models.py
- sv/static/sv/fichezonedelimitee_detail.css
- sv/templates/sv/fichezonedelimitee_detail.html
- sv/templates/sv/fichezonedelimitee_form.html
- sv/tests/test_fichezonedelimitee_create.py
- sv/tests/test_fichezonedelimitee_update.py
- sv/tests/test_utils.py
- sv/urls.py
- sv/views.py
Cette PR permet la modification d'une fiche zone délimitée.
* [`sv/forms.py`](diffhunk://#diff-6f19058e639b4056f4b36590a53efce272797f93b7f15657b338da70eff6ffc6L152-R155): Mise à jour de l'initialisation des forms (passage de `organisme_nuisible_libelle` et `fiche_zone_delimitee`). [[1]](diffhunk://#diff-6f19058e639b4056f4b36590a53efce272797f93b7f15657b338da70eff6ffc6L152-R155) [[2]](diffhunk://#diff-6f19058e639b4056f4b36590a53efce272797f93b7f15657b338da70eff6ffc6L230-R246)
* [`sv/forms.py`](diffhunk://#diff-6f19058e639b4056f4b36590a53efce272797f93b7f15657b338da70eff6ffc6L266-R277): Suppression du code pour le passage de l'organisme nuisible dans `ZoneInfesteeFormSet` et ajout d'un nouveau formset `ZoneInfesteeFormSetUpdate` pour afficher un form `ZoneInfesteeForm` vide uniquement en cas …
> Modification fiche zone délimitée

- sv/tests/test_fichedetection_update.py
- sv/views.py
Ce commit corrige le cas où l'on créé un lieu et un prélèvement sans date.
Fixes SEVES-Y
> Corriger les prélèvements sans date

- core/fields.py
- core/mixins.py
- sv/forms.py
- sv/managers.py
- sv/models.py
- sv/static/sv/fichezone_detail.js
- sv/static/sv/fichezone_form.js
- sv/templates/sv/fichezonedelimitee_detail.html
- sv/templates/sv/fichezonedelimitee_form.html
- sv/tests/test_fichedetection_create.py
- sv/tests/test_fichedetection_performances.py
- sv/tests/test_fichezonedelimitee_add_performance.py
- sv/tests/test_fichezonedelimitee_create.py
- sv/tests/test_fichezonedelimitee_detail_performances.py
- sv/tests/test_fichezonedelimitee_update.py
- sv/tests/test_fichezonedelimitee_update_performance.py
- sv/urls.py
- sv/views.py
Ce commit ajoute la gestion des liens libres depuis la création et l'édition de fiche zone tout en netoyant le code restant de l'ancienne version.
Limite aussi la liste des liens libres potentiels au fiche visible par l'utilisateur
> Ajouter les liens libres sur les fiches Zone

- cron.json
En attendant un ClockProcess ou une file...
> Augmenter la fréquence du cron de mail

- sv/static/sv/common.css
- sv/static/sv/fichedetection_detail.css
- sv/templates/sv/fichedetection_detail.html
- sv/templates/sv/fichezonedelimitee_detail.html
Uniformise le style des boutons d'action des fiches détection et zone. Uniformise les balises et le style utilisé.
Fixes #439
> Corriger l'affichage du bouton modifier de la zone

- sv/templates/sv/fichedetection_detail.html
> Changer le vocabulaire pour un prélèvement positif

- sv/forms.py
- sv/static/sv/fichedetection_form.js
- sv/static/sv/fichezone_form.js
- sv/tests/test_fichedetection_create.py
- sv/tests/test_fichedetection_detail.py
- sv/tests/test_fichezonedelimitee_create.py
- sv/views.py
Afin d'afficher les fiches les plus récentes en premier.
> Trier les fiches par numéro dans les liens libres

- sv/tests/test_fichezonedelimitee_visibilite_access.py
- sv/views.py
Filtrer la liste de fiche zone sur les fiches qui sont réellement accessible a l'utilisateur.
> Filtrer la liste de fiche zone

- sv/display.py
- sv/managers.py
- sv/models.py
- sv/static/sv/fiche_list.css
- sv/templates/sv/fiche_list.html
- sv/tests/test_fiches_search.py
- sv/tests/test_managers.py
- sv/views.py
Pour chaque type de fiche ajoute le nombre de lien dans le tableau de liste.
> Ajouter le nombre de liens dans la liste

- core/templates/core/message_detail.html
Ticket Notion : https://www.notion.so/incubateur-masa/S-parer-les-contacts-par-des-points-virgules-14dde24614be8198bfbdd8142b5b3c5b?pvs=4
> Ajoute un point-virgule entre les contacts d’un message (destinataires et copie) lors de sa consultation

- core/mixins.py
- sv/tests/test_fichedetection_ac_notification.py
Cette PR permet d'ajouter le BSV et la MUS dans la liste des contacts de la fiche lorsque l'AC est notifiée (action 'Déclarer à l'AC) depuis une fiche.
Issue Notion : https://www.notion.so/incubateur-masa/Ajout-automatique-AC-si-notifi-e-d-une-alerte-14dde24614be81d1ab73d051d52e90d0?pvs=4
> Ajout BSV et MUS dans les contacts de la fiche lorsque l'AC est notifiée

- sv/forms.py
- sv/templates/sv/fichedetection_detail.html
Afin de le rendre plus explicite.
> Renommer le label des végétaux infestés

- requirements.in
- requirements.txt
- sv/factories.py
- sv/tests/conftest.py
- sv/tests/test_fichedetection_form.py
- sv/tests/test_fiches_search.py
Introduction de certaines factories (encore basiques et incomplètes) et réecriture de quelques tests.
> Introduire des factories pour les tests

- core/notifications.py
- sv/tests/test_notifications.py
- Les mails sont maintenant envoyés au format HTML
- La structure est la même quelque soit le type d’élément de suivi envoyé
- Création d'un objet de type `EmailTemplate` pour gérer le template HTML via `django post office`
- Suppression du message automatique car maintenant c'est le contenu que l'agent a entré lors de la rédaction qui est affiché dans le corps du mail (sauf pour la notification AC)
- Dans le template HTML,  styles CSS appliqués directement dans les balises HTML pour maximiser la compatibilité avec les différents clients email (cf. score Mailtrap)
- Dans les tests de notifications, renomme les variables pour éviter l'ambiguïté entre le contenu du message et l'objet Message lui-même :
- `message` en `content` pour le contenu textuel
- `instance` en `message_obj` pour …
> Emails de notifications au format HTML

- sv/templates/sv/fichedetection_form.html
Ticket Notion : https://www.notion.so/incubateur-masa/UI-Mise-en-place-d-un-composant-information-14dde24614be810e89f3da82b2896856?pvs=4
> Ajout du composant d'information du DSFR dans le bloc prélèvement du formulaire de la fiche détection

- core/templates/core/_carte_resume_document.html
Ticket Notion : https://www.notion.so/incubateur-masa/Ticket-de-recette-158de24614be80d488c2d9b9f2228cd7?pvs=4
> Améliore l'agencement des icônes d'actions d'un document

- sv/forms.py
- sv/templates/sv/fichezonedelimitee_detail.html
Ticket Notion : https://www.notion.so/incubateur-masa/Changer-le-nom-caract-ristique-de-la-zone-15fde24614be80ab97facb18e73f7da6?pvs=4
> Modification du label Caractéristique en Caractéristique principale dans une ZI d'une fiche zone délimitée

- sv/display.py
- sv/static/sv/fiche_list.css
- sv/static/sv/fiche_list.js
- sv/templates/sv/fiche_list.html
- sv/tests/test_fichedetection_list.py
- sv/tests/test_fiches_search.py
- Changement d'icone si l'événement est déclaré à l'AC ou non
- Changement de la navigation pour avoir un seul lien par ligne
- Affichage des zones / détections dans la dernière colonne
- Corrections de tous les tests liés
> Améliorer la vue de liste de fiches

- sv/display.py
- sv/forms.py
- sv/managers.py
- sv/tests/test_evenement_performance_details.py
- sv/tests/test_export.py
- sv/tests/test_fiche_list_performances.py
- sv/tests/test_fichezonedelimitee_add_performance.py
- sv/views.py
Réduit le nombre de requêtes SQL faites a plusieurs endroits de l'application et corrige les tests en conséquence. Le code est encore optimisable a plusieurs endroits, j'ai essayé de rendre les pages les plus importante plus rapide a charger quand il y a beaucoup d'objets liés.
> Améliorer les performances, réduire le nombre de queries

- core/static/core/base.css
- sv/form_mixins.py
- sv/forms.py
- sv/managers.py
- sv/mixins.py
- sv/models/evenements.py
- sv/models/fiches_detection.py
- sv/models/fiches_zone_delimitee.py
- sv/static/sv/evenement_details.css
- sv/static/sv/evenement_form.css
- sv/static/sv/evenement_form.js
- sv/static/sv/fichedetection_form.css
- sv/templates/sv/_evenement_action_navigation.html
- sv/templates/sv/_evenement_badges.html
- sv/templates/sv/_list_free_links.html
- sv/templates/sv/evenement_detail.html
- sv/templates/sv/evenement_form.html
- sv/templates/sv/fichedetection_form.html
- sv/templates/sv/fichezonedelimitee_form.html
- sv/tests/test_evenement_performance_details.py
- sv/tests/test_evenement_update.py
- sv/tests/test_fichezonedelimitee_add_performance.py
- sv/urls.py
- sv/view_mixins.py
- sv/views.py
Ce commit permet l'édition d'un événément afin d'en modifier les descripteurs (ON, status) et des gérer les liens libres. J'ai du retirer du code lié aux liens libres qui était encore utilisé dans le code des fiches.
> Permettre d'éditer un événement

- sv/tests/test_evenement_ac_notification.py
- sv/tests/test_fichedetection_create.py
- sv/tests/test_fichezonedelimitee_detail.py
Ce commit corrige des tests qui étaient "skip" suite au refacto de l'ajout de l'événement dans le projet.
> Corriger des tests non exécutés

- sv/factories.py
- sv/tests/test_evenement_performance_details.py
- sv/tests/test_models.py
- sv/views.py
Utilisation de Prefetch avec select_related pour charger les données liées aux prélèvements (matrice, espèce, laboratoire) en une seule requête plutôt que trois requêtes distinctes
Gestion des structures via des traits : 
- choix aléatoire par défaut parmi toutes les structures, 
- trait non_exploitant pour exclure STRUCTURE_EXPLOITANT,
- simplification associée de PrelevementFactory pour utiliser ces traits.
- réorganisation des attributs pour avoir le même ordre que l'objet Prelevement (cf. model) sauf pour les lazy_attribute
- utilisation de lazy_attribute pour garantir la génération de données valides et respecter automatiquement les règles métier :
- structure preleveuse non-Exploitant pour les prélèvements officiels
- laboratoire de confirmation officielle pour les prélèvements de …
> Mise à jour de la factory Prelevement  + optimisation des requêtes dans EvenementDetailView

- sv/tests/test_fichezonedelimitee_create.py
- sv/tests/test_fichezonedelimitee_update.py
Fait revenir des tests dans la suite de tests.
> Rajouter des tests suite au refacto de l'événement

- sv/templates/sv/evenement_detail.html
- sv/tests/test_evenement_details.py
- sv/tests/test_fichezonedelimitee_detail.py
Ajoute des informations supplémentaires dans le bloc d'information de l'événement.
> Compléter les informations sur l'événement

- sv/display.py
- sv/templates/sv/fiche_list.html
- sv/tests/test_fichedetection_list.py
- Ajoute redirection vers l'onglet zone lors d'un clic sur une zone dans le tableau
- Ajoute redirection vers l'onglet détection avec sélection lors d'un clic sur une détection
> Navigation depuis liste des fiches vers onglets zone et détection

- core/management/commands/export_contacts_structures.py
- core/management/commands/import_contacts.py
- core/management/commands/update_contacts_structures_email.py
- core/tests/test_export_contacts_structures.py
- core/tests/test_import_contacts.py
- core/tests/test_update_contacts_structures_email.py
- fake_contacts.csv
- fake_contacts_structures.csv
- modification du fichier `fake_contacts.csv`pour intégrer structures SV et 5 agents par structures
- ajout du fichier `fake_contacts_structures.csv` avec adresse email pour chaque structure
- modification du séparateur (`,` à la place de `;`)
> Mise à jour du fichier fake_contacts.csv pour intégrer les structures de SV et modification du séparateur

- sv/forms.py
- sv/static/sv/fichezone_form.css
- sv/static/sv/fichezonedelimitee_detail.css
- sv/templates/sv/_fichezonedelimitee_detail_zone_tampon.html
- sv/templates/sv/_fichezonedelimitee_detail_zones_infestees.html
- sv/templates/sv/_fichezonedelimitee_form_zones_infestees.html
- sv/templates/sv/_list_free_links.html
- sv/templates/sv/fichezonedelimitee_detail.html
- sv/templates/sv/fichezonedelimitee_form.html
- sv/tests/test_evenement_details.py
- sv/tests/test_evenement_performance_details.py
- sv/tests/test_fichedetection_list.py
- sv/tests/test_fichezonedelimitee_add_performance.py
- sv/tests/test_fichezonedelimitee_create.py
- sv/tests/test_fichezonedelimitee_detail.py
- sv/tests/test_fichezonedelimitee_update.py
Ticket Notion : https://www.notion.so/incubateur-masa/R-organisation-des-formulaires-de-la-zone-183de24614be8031a6a8fb2efd856712?pvs=4
> Réorganisation formulaire et détail fiche zone

- sv/tests/test_utils.py
Corrige un test qui fail sur main (car certains éléments du formulaire de la fiche zone ont changé d'emplacement)
> Corrige un test qui fail sur main

- account/tests/test_handle_permission_view.py
- core/static/core/base.css
- core/templates/core/base.html
Utilisation du composant DSFR et personalisation pour nos propres besoins (bouton bleu dans la navigation, menu déroulant, ajout du tag SV, etc.)
> Rendre le header responsive

- sv/filters.py
- sv/tests/test_fiches_search.py
Assouplir les règles afin de pouvoir trouver facilement toutes les fiches d'une année ou d'un événement.
> Améliorer la recherche par numéro

- sv/models/evenements.py
- sv/templates/sv/fichedetection_form.html
- sv/templates/sv/fichezonedelimitee_form.html
- sv/urls.py
- sv/views.py
Plutôt que d’accéder à un évènement avec l’identifiant technique (pk), on y accède avec son numéro (2025.12)
> Modification de l'URL d'accès à un évènement

- core/fields.py
- core/forms.py
- sv/tests/test_evenement_message.py
Afficher le nom de la structure après le nom et le prénom du contact.
> Afficher les structures sur les contacts

- sv/templates/sv/_list_free_links.html
- sv/templates/sv/evenement_detail.html
- sv/tests/test_evenement_update.py
Modifications mineures pour améliorer l'expérience utilisateur.
> Améliorer l'interface des liens libres

- core/static/core/fil_de_suivi.css
- core/templates/core/_tableau_fil_de_suivi.html
Afin que l'on ai accès à la liste complète sans ouvrir le message.
> Montrer les destinataires dans un tooltip

- sv/static/sv/fiche_list.js
- sv/tests/test_fiches_search.py
Afin que les données affichées correspondent toujours aux filtres.
> Soumettre le formulaire au clic sur effacer

- core/static/core/base.css
- sv/static/sv/fiche_list.css
- sv/templates/sv/_evenement_badges.html
Même style que dans la vue de liste quand un événement est notifié AC.
> Unifier le badge déclaré à l'AC

- sv/static/sv/fichedetection_lieux_form.js
- sv/tests/test_fichedetection_create.py
- Exclusion des établissements ayant été fermé a un moment de leur existence
- Ajout du code postal et de la commune dans l'adresse
> Améliorer la recherche via SIRENE

- sv/static/sv/fichezonedelimitee_detail.css
- sv/templates/sv/_fichezonedelimitee_cartographies.html
- Utilisation du curseur pointeur pour montrer le côté intéractif
- Changement de ratio des images
> Améliorer la gallerie de cartographies

- core/static/core/message_form.js
- core/templates/core/_carte_resume_contact_agent.html
- core/templates/core/_carte_resume_contact_structure.html
- sv/tests/test_evenement_contacts_list.py
Lorsqu'on clic sur le mail d'un contact proposer l'écriture d'un message plutôt que d'un mail.
> Permettre d'écrire un message au clic sur le contact

- core/mixins.py
> Améliorer la gestion des erreurs de l'API INSEE

- core/templates/core/base.html
- sv/templates/sv/base.html
Et l'étendre au besoin dans les autres applications.
> Rendre le template core/base.html générique

- sv/admin.py
- sv/models/evenements.py
- sv/tests/test_fichedetection_create.py
Erreur Sentry : SEVES-46 + affichage des évènements supprimés dans l'admin.
> Fix erreur ajout évènement  lorsque le dernier évènement est supprimé

- .pre-commit-config.yaml
https://github.com/thoughtworks/talisman
> Ajouter Talisman pour empécher le commit de secrets

- .talismanrc
- bin/fetch_contacts_agricoll_and_key.sh
- core/tests/test_fetch_and_import_contacts.py
MAJ du script de récupération du fichier de données correspondant à l'export Agricoll pour gérer la décompression (zip).
> MAJ script et test pour gérer fichier agricoll zippé

- sv/tests/test_evenenement_visibilite_update.py
- sv/views.py
Ajoute les structures sélectionnées dans le formulaire de visibilité limitée dans la liste des contacts de l'évènement
> Ajout dans les contacts si visibilité limitée

- .talismanrc
- ssa/static/ssa/_rappel_conso_form.js
- ssa/templates/ssa/evenement_produit_form.html
Pour les inputs de rappel conso, passer automatiquement au champ suivant quand le nombre max de caractères est atteint.
> Passer automatiquement au champ suivant pour les rappel conso

- conftest.py
- core/static/core/base.css
- core/templates/core/base.html
- core/tests/test_context_processor.py
- seves/context_processors.py
- seves/middlewares.py
- seves/settings.py
- ssa/templates/ssa/base.html
- ssa/tests/test_evenement_produit_details_performances.py
- ssa/tests/test_evenement_produit_list_performances.py
- sv/templates/sv/base.html
- sv/tests/test_evenement_performance_details.py
- sv/tests/test_fiche_list_performances.py
- sv/tests/test_fichezonedelimitee_add_performance.py
- sv/tests/test_fichezonedelimitee_update_performance.py
Quand un utilisateur à les droits dans plusieurs domaines, permettre de changer de domaine en utilisant l'interface.
> Permettre de changer de domaine

- core/templates/core/base.html
- sv/static/sv/evenement_details.css
- Même identifiant entre deux picker : conflit au niveau du comportement
- Correction visuelle du picker de domaine sur la page de détails
> Corriger le sélecteur de message

- ssa/tests/pages.py
Changement de classe de CSS lors d'un refacto précédent
> Corriger un test sur main

- ssa/templates/ssa/evenement_produit_detail.html
- ssa/tests/test_evenement_produit_details_performances.py
Dans le commit 1ba3356d54d34ab194f1102f14bfe241efee8a31 la modification n'avait pas bien été répercutée sur le template SSA.
> Corriger la date de dernière modification dans SSA

- ssa/static/ssa/evenement_produit_form.js
On veut garder le tri que nous avons défini.
> Retirer le tri sur les unité de quantification

- core/mixins.py
- core/views.py
- ssa/tests/test_evenement_produit_creation.py
- ssa/views/produit.py
- sv/view_mixins.py
- sv/views.py
Dans SSA à la création d'un événement produit ajouter le créateur et sa structure dans les contacts de la fiche (iso SV).
> Ajouter automatiquement le créateur dans les contacts

- core/views.py
- sv/tests/test_evenement_message.py
Le changement principal concerne le traitement des référents nationaux lors de l'ajout d'un message : lorsqu'un référent national est le seul représentant de sa structure parmi les destinataires, cette structure n'est pas ajoutée.
> Gestion des référents nationaux dans les messages

- account/forms.py
- account/static/account/base.css
- account/templates/user_permissions.html
- account/tests/test_handle_permission_view.py
- account/views.py
Modification UI “gestion des droits d’accès” pour activer/desactiver l'accès à SV et/ou SSA.
> Gestion des droits d'accès par domaine (SV, SSA)

- core/static/core/view_manager.js
- core/templates/core/_details_toogle.html
- ssa/static/ssa/evenement_produit_detail.js
- ssa/templates/ssa/evenement_produit_detail.html
- sv/static/sv/evenement_details.js
- sv/templates/sv/evenement_detail.html
- sv/tests/test_evenement_details.py
Refactoring de l'existant pour permettre de cacher plusieurs blocs.
> Ajouter l'affichage en synthèse sur SSA

- core/static/core/view_manager.js
- ssa/templates/ssa/_evenement_produit_informations.html
- ssa/templates/ssa/_evenement_produit_informations_synthese.html
- ssa/templates/ssa/evenement_produit_detail.html
Afficher un bloc de résumé plutôt que des masquer des informations dans des blocs existants.
> Améliorer le comportement de la synthése sur SSA

- ssa/static/ssa/evenement_produit_list.css
- ssa/templates/ssa/evenementproduit_list.html
- Correction du HTML pour fermer le bloc au bon endroit
- Changement de marge pour coller avec le corps du contenu
> Améliorer le rendu de la vue de liste SSA

- ssa/filters.py
- ssa/tests/pages.py
- ssa/tests/test_evenement_produit_list.py
Oublié dans le lot sur les filtres avancés.
> Ajouter un filtre sur le siret/siren

- ssa/static/ssa/evenement_produit_detail.css
- ssa/templates/ssa/_evenement_produit_informations.html
- ssa/templates/ssa/_evenement_produit_informations_synthese.html
- ssa/templates/ssa/_modal_etablissement_details.html
- ssa/templates/ssa/evenement_produit_detail.html
- ssa/templatetags/or_empty_value_tag.py
Pour éviter la confusion avec Non Conformité (NC).
> Changer la valeur vide par défaut dans SSA

- ssa/static/ssa/_etablissement_form.js
- ssa/templates/ssa/_etablissement_modal.html
- ssa/tests/test_evenement_produit_creation.py
- sv/tests/test_evenement_search.py
Ce code ne s'éxecute pas lors des tests, conformément à ce qui a été décidé. Cette PR n'introduit donc pas de nouveau tests.
> Récupération de la valeur du département lors d'une recherche SIRENE

- pytest.ini
- ssa/factories.py
- ssa/models/evenement_produit.py
- sv/factories.py
- Définir un marqueur personalisé
- Utiliser une timezone pour les dates extraites
- Utiliser les nouvelles syntaxes pour les conditions/check
https://docs.pytest.org/en/stable/how-to/mark.html
> Retirer quelques warnings dans les tests

- core/managers.py
- ssa/managers.py
- sv/managers.py
- tiac/filters.py
- tiac/managers.py
- tiac/mixins.py
- tiac/models.py
- tiac/templates/tiac/base.html
- tiac/templates/tiac/evenementsimple_list.html
- tiac/tests/pages.py
- tiac/tests/test_evenement_list.py
- tiac/urls.py
- tiac/views.py
Add a basic list view pour Evenement Simple
- Try to remove some duplicate code in the managers
- Adding a list view similar to the one in SSA (EvenementProduit), the filter is already there but empty in order to ease the introduction of the filters
> Add list view for Evenement Simple

- ssa/models/evenement_produit.py
We want the users to pick the finest value of danger if possible.
> Change most common values for dangers

- core/static/core/forms.mjs
- tiac/forms.py
- tiac/static/tiac/etablissements.mjs
- tiac/static/tiac/repas.mjs
- tiac/templates/tiac/forms/etablissement.html
- tiac/templates/tiac/forms/etablissement_base_set.html
- tiac/tests/test_evenement_simple_etablissement.py
- Implémentation du l'interrupteur inspection
- Ajout styles encart inspection
- Manque tests
> Encart inspection

- tiac/templates/tiac/evenement_simple.html
- tiac/templates/tiac/evenement_simple_modification.html
- tiac/tests/pages.py
- tiac/tests/test_evenement_simple_modification.py
- tiac/views.py
> Fixes de la recette sur la modification d'enregistrements simples
