betagouv/seves

.github/workflows/django.yml
pytest.ini
sv/tests/conftest.py

- Permet de lancer les tests et ruff à chaque commit
- Réduit le timeout à 2 secondes par page afin que les test prennents moins de temps en cas de problème / attente du navigateur
- Lance les tests en parallèle en fonction des capacités de la machine
- Lance le formatage des templates en excluant les dépendances
https://github.com/rtts/djhtml/issues/48

Ajout d'une configuration pour la CI

---

sv/static/sv/base.css
sv/templates/sv/base.html
sv/templates/sv/fichedetection_detail.html

Déplace le templating des messages Django d'un template d'une vue au template générique de base afin de pouvoir profiter du système de messages dans l'ensemble des vues.
Ajoute la gestions des différents styles (info, error, etc) via les tags.

Déplace et améliore la gestions des messages

---

scalingo.json

Lors de la création d'une review app sur scalingo, la variable d'environnement ALLOWED_HOSTS prend comme valeur l'url automatiquement. 
Exemple : pour ma review app "seves-recette-pr92", la valeur de ALLOWED_HOSTS doit égal à seves-recette-pr92.osc-fr1.scalingo.io

Configuration automatique ALLOWED_HOSTS

---

core/forms.py
core/mixins.py
core/templates/core/_carte_resume_document.html
core/templates/core/_modale_edition_document.html
core/urls.py
core/views.py
sv/tests/test_fichedetection_documents.py

Permet d'éditer les descripteurs d'un document (nom, description et type) afin de pouvoir corriger une erreur / faute d'orthographe / etc.
Petite correction d'une faute d'accent sur un message de confirmation.
Renommage du champs description en commentaire (remontée atelier).

Permettre d'éditer les descripteurs d'un document

---

core/templates/core/_modale_edition_document.html

S'assure que quand on ferme la modale d'édition de document le formulaire n'est pas envoyé en sortant le boutton du form.

Corrige la fermeture de la modale d'édition

---

scalingo.json

Sur scalingo, les URL des review app étant dynamique, elles ne peuvent pas être déclarées à l'avance dans le portail EAP.
Donc, erreur de connexion lors du login.
Ajout d'une configuration pour utiliser le portail de test oidctest.wsweet.org seulement pour les review app.

Configuration du endpoint OIDC pour les review app Scalingo

---

.github/workflows/django.yml
bin/check_html_format.sh
core/templates/core/_dsfr_div.html
core/templates/core/login.html
sv/templates/sv/base.html

Le code de status n'était pas le bon car il est "avalé" par xargs, qui renvoit son propre code de status. Utilisation d'un petit script pour corriger le problème.

Corrige le script de détection des erreurs HTML

---

sv/templates/sv/fichedetection_list.html
sv/views.py

Cette PR implémente une pagination fixée à 100 items par page et masque les contrôles de pagination si les résultats tiennent sur une seule page.

Pagination à 100 items + masquage si une seule page

---

sv/static/sv/fichedetection_detail.css
sv/templates/sv/_fichedetection_synthese.html
sv/templates/sv/fichedetection_detail.html

Améliore le rendus des descripteurs de la fiche détection en mode "Synthèse" en passant les descripteurs sur 3 colonne (cf maquette).

Améliorer le rendus des descripteurs en synthèse

---

core/templates/core/_documents.html
core/templates/core/_fiche_bloc_commun.html
core/templates/core/_messages.html
core/templates/core/base.html
core/views.py
sv/static/sv/fichedetection_detail.js
sv/tests/test_fiche_detection_message.py
sv/tests/test_fichedetection_documents.py

Ce commit a pour but de corriger le plus gros problème d'interaction remonté lors de la review design: lors d'un action dans le bloc commun le navigateur doit arriver au niveau du bloc concerné (ancre) et avec le bon onglet d'ouvert, le message de feedback doit être dans le bloc concerné.
- Introduction d'une mécanique pour identifier les messages a afficher en haut et ceux a afficher dans un bloc particulier
- Utilisation d'ancre pour amener le navigateur directement au bon bloc
- Utilisation d'anche pour ouvrir le bon onglet du bloc commun. Lors d'un commit précédent j'avais introduit un petit bout de JS pour cela, mais en relisant la doc du DSFR (voir notes) je me suis rendu compte que cela était possible directement avec une ancre
- Retrait d'un mécanisme de vérification sur la …

Corriger le design du bloc commun

---

.pre-commit-config.yaml
core/management/commands/generate_fake_contacts.py
fake_contacts.csv
requirements.in
requirements.txt

Cette PR introduit une commande Django permettant la génération d'une liste de contacts fictifs dans le fichier fake_contacts.csv à partir du fichier d'extraction Agricoll (fourni par le MASA). 
Le fichier `fake_contacts.csv` est inclus à la racine du projet pour pouvoir être utilisé par la suite sans devoir exécuter à nouveau la commande.
Cette commande permet également de spécifier un nombre limité de contacts à anonymiser grâce à l'option `--count`. 
Le fichier généré peut être utilisé pour importer des données de contacts dans l'environnement de développement et de recette, évitant ainsi d'utiliser des données de contacts de production dans ces environnements.
Pour générer des données fictives, la commande utilise la bibliothèque faker.
Commandes d'utilisation :
- Générer tous les …

Génération fichier CSV contenant des contacts fictifs

---

core/static/core/base.css
core/templates/core/base.html
sv/static/sv/fichedetection_form.css
sv/static/sv/fichedetection_list.css
sv/static/sv/fichedetection_list.js
sv/templates/sv/fichedetection_form.html
sv/tests/test_fichedetection_search.py
sv/views.py

Permet que le champ de filtre sur les organismes nuisibles soit cherchable en utilisant Choices.js.
Factorisation de la bibliothéque au niveau du template de base.

Rendre le champs des organismes nuisibles cherchable

---

core/templates/core/_tableau_fil_de_suivi.html
core/templates/core/base.html

Permet d'utiliser des icônes qui ne seraient pas dans le DSFR.

Ajouter Remixicon pour avoir des icônes hors DSFR

---

core/filters.py
sv/tests/conftest.py
sv/tests/test_fichedetection_documents.py

Dans l'onglet Documents ce commit va permettre de filtrer sur les unités a l'origine de l'upload d'un document.
J'ai revu le fonctionnement des deux filtres pour ne lister que les valeurs possibles extraites de la liste des documents. Ainsi on affiche que les types de documents présents dans la liste (il n'est pas possible de filtrer sur Cartographie si il n'y a pas de Cartographie dans les documents). De même pour les unités, afin d'éviter de présenter des centaines d'unités si la fiche que fait intervenir que quelques unités.

Permettre de filtrer sur les unités - Documents

---

sv/templates/sv/_fichedetection_synthese.html
sv/views.py

Travail en cours (review app) -> https://seves-recette-pr192.osc-fr1.scalingo.io/sv/fiches-detection/1/
Affichage du 1er lieu enregistré et le nombre de lieux restant (sur vue synthèse fiche détection)
et ajout d'un tooltip pour afficher le reste des communes :

Affichage du 1er lieu enregistré et le nombre de lieux restant (sur vue synthèse fiche détection)

---

core/static/core/bloc_commun.css
core/templates/core/_fiche_bloc_commun.html

Ajout d'une hauteur minimale pour l'affichage du bloc commun : 
- ajout des classes css suivant BEM pour chaque onglet
- 600px pour la hauteur minimale

Ajout d'une hauteur minimale pour l'affichage du bloc commun

---

sv/templates/sv/fichedetection_detail.html

Affichage de la date de prélèvement lors de la consultation d'une fiche détection et ajout d'une icône lorsque c'est un prélèvement officiel

Affichage de la date de prélèvement sur consultation d'une fiche détection

---

core/forms.py
core/static/core/contact_add_form.css
core/templates/core/_contact_add_form.html
core/templates/core/_contact_checkbox.html
core/templates/core/_contacts.html
sv/tests/test_contact_add.py

Cette PR apporte quelques modifications pour respecter le design du formulaire d'ajout de contacts sur une fiche détection : 
- Liste des contacts sur 2 colonnes
- Suppression de l'affichage de la structure dans les résultats
- Fond blanc + padding/margin

Ajustement design sur le formulaire d'ajout de contact

---

sv/tests/test_fichedetection_create.py
sv/views.py

Ce commit permet l'ajout du créateur d'une fiche détection en tant que contact par défaut de la fiche. Pour le moment n'est pas généralisé car je ne sais pas si cela doit être fait pour les autres types de fiches. Autre pistes:
- Mettre la logique dans le save de l'objet
- Utiliser un signal pour ajouter le contact

Ajouter le créateur en tant que contact par défaut

---

core/mixins.py
core/templates/core/_carte_resume_contact.html
core/templates/core/_modale_suppression_contact.html
core/urls.py
core/views.py
sv/tests/test_fichedetection_contacts_remove.py

Ce commit permet de retirer un contact d'une fiche si il ne fait plus partie de l'équipe en charge du traitement de la fiche. On peut retirer un autre contact ou bien soi-même.

Permettre la suppression d'un contact d'une fiche

---

sv/export.py
sv/tests/test_export.py

Ce commit va permettre l'extraction des informations d'une fiche détection au format CSV. Ce commit n'introduit que la base sans interface pour lancer l'export pour le moment (en attente de design). Les tests vérifient le contenu du fichier, les règles métiers sur le nombre de lignes dans le fichiers ansi que la performance en termes de requêtes SQL.

Permettre l'extraction des fiches en CSV

---

core/mixins.py
core/templates/core/_carte_resume_document.html
core/templates/core/_tableau_fil_de_suivi.html
sv/tests/test_fichedetection_performances.py
sv/views.py

Le but de ce commit est de tester et d'améliorer les performances de la page de détails d'une fiche détection (et des autres types de fiche dans le futur pour les objects communs).
- Mise en place de tests pour vérifier la "scalabilité" de la page en termes de requêtes SQL face a l'accroissement du nombre d'objets
- Diverses améliorations de performances : prefetch related, select related et "cache" de l'objet courant dans la vue de détails.
En local sur une page test (plusieurs messages, documents, lieux, prélévements, etc.) on passe de 137 requêtes à 25 requêtes.

Améliorer et tester les perfs de la page fiche

---

pytest.ini
seves/settings.py

Nous avons régulierement des tests qui échouent de manière occasionnelle, avec comme erreur un message comme:
test_can_filter_documents_by_type_on_fiche_detection - django.db.utils.IntegrityError: insert or update on table "core_document" violates foreign key constraint "core_document_content_type_id_f051a534_fk_django_co"
Le même test peut réussir au lancement suivant et réussir quand il est lancé individuellement. En creusant je me suis rendu compte que `get_for_model` qui est utilisé dans la fixture `document_recipe` utilise du cache pour le content type. Le fait de ne pas mettre de vrai backend de cache dans les settings de test semble corriger le problème.

Tenter de corriger les problèmes de tests

---

sv/tests/test_fichedetection_update.py
sv/views.py

Cette PR ajoute la sauvegarde des coordonnées GPS lamber93 lors de la création d'une fiche détection.

Cordonnées GPS Lambert93 création fiche détection

---

sv/templates/sv/fichedetection_list.html

Cette PR permet de masquer le tableau de listing des fiches détection si aucune fiches existe en bd.
Avant : 
Après :

Masque le tableau si aucune fiche en bd

---

sv/templates/sv/_fichedetection_synthese.html
sv/templates/sv/fichedetection_list.html

Cette PR corrige l'affichage des communes d'un lieu lié à une fiche détection.
Actuellement, lorsqu'un lieu est enregistré dans une fiche détection mais que celui-ci ne possède de commune, voici l'affichage sur la liste des fiches et le détail de la fiche :

Affichage de nc. quand la commune du lieu est vide

---

sv/static/sv/fichedetection_list.css
sv/templates/sv/_extract_modal.html
sv/templates/sv/fichedetection_list.html
sv/tests/test_fichedetection_export.py
sv/urls.py
sv/views.py

Fait juste le branchement entre l'interface et le code existant pour permettre les téléchargement de toute les fiches.

Permettre d'extraire les fiches détection en CSV

---

core/fields.py
core/forms.py
core/managers.py
core/models.py
core/templates/core/_fil-de-suivi.html
core/templates/forms/dsfr_checkbox_option.html
sv/tests/test_fiche_detection_message.py

Pour les compte rendus sur DI permet de sélectionner un destinataire au choix entre la MUS ou le BSV (ou les deux) et envoi le message au bon destinataire.
Ajout d'un champ de formulaire pour les checkbox DSFR.

Permettre de sélectionner un destinataire - Compte rendu

---

sv/tests/test_fichedetection_create.py
sv/views.py

Cette PR permet d'ajouter la structure de l'agent créateur de la fiche détection à la liste des contacts de la fiche détection.
Actuellement, seul l'agent est ajouté dans la liste des contacts.

Ajout structure à la liste des contacts lors de la création d'une fiche détection

---

core/mixins.py
core/models.py
sv/managers.py
sv/models.py
sv/templates/sv/_action_navigation.html
sv/templates/sv/_fichedetection_cloturer_modal.html
sv/templates/sv/fichedetection_detail.html
sv/tests/test_fichedetection_etats.py
sv/tests/test_fichedetection_performances.py
sv/tests/test_fichedetection_update.py
sv/tests/test_structure_add.py
sv/urls.py
sv/views.py

Cette PR ajoute l'état `clôturé` sur la fiche détection.

Ajout le l'état `clôturé`

---

core/redirect.py
core/views.py
sv/views.py

Corrige quelques "open redirect" qui peuvent arriver au sein de l'outil si un utilisateur manipule le payload. Très peu probable car il faudrait forger le contenu du formulaire pour rediriger un utilisateur tiers.
Ca fera plaisir au bot.

Corrige des redirections ouvertes sur paramètre POST

---

sv/templates/sv/_action_navigation.html
sv/tests/test_fichedetection_ac_notification.py

Redirige vers la fiche en question plutôt que vers la liste.
Corrige #294

Changer la redirection après notification à l'AC

---

sv/templates/sv/fichedetection_detail.html

Ajout des labels devant les descripteurs sur la vue détails d'une fiche détection.
Corrige #298

Ajouter les labels devant les descripteurs

---

sv/static/sv/fichedetection_form.js
sv/templates/sv/fichedetection_form.html
sv/tests/test_fichedetection_update.py

Lorsqu'on valide une fiche détection sans changer la valeur de l'organisme nuisible celle-ci est perdue. Dans le code on mélange pour le moment deux type de valeur, des entiers et des objets en fonction de si le select a été utilisé par l'utilisateur ou non.

Corriger un bug lors de l'édition de la fiche détection

---

account/static/account/base.css
account/templatetags/groups.py
account/tests/test_handle_permission_view.py
core/templates/core/base.html
sv/tests/test_fichedetection_performances.py

- Cacher le menu si l'utilisateur n'a pas les droits pour consulter la page.
- Améliorer la lisibilité en augmentant les marges dans la grille.

Améliorer la page de gestion des droits

---

core/forms.py
core/static/core/message.css
core/static/core/message_form.js
core/templates/core/_contact_add_form.html
sv/tests/test_fiche_detection_message.py

Permet d'ajouter toutes les structures d'une fiche en tant que destinataire et/ou copie en un seul clic.
Embarque une mise à jour de la bibliothèque pour bénéficier de l'amélioration drastique des performances sur les listes longues (ce qui est notre cas): https://github.com/Choices-js/Choices/issues/816 .

Ajouter les structures en un clic au message

---

sv/static/sv/fichedetection_form.js
sv/templates/sv/_fichedetection_form__lieux_form.html
sv/templates/sv/_fichedetection_form__prelevements_form.html
sv/templates/sv/fichedetection_form.html
sv/views.py

Le but de cette PR refactorise la manière dont les données des listes déroulantes sont passées au template dans le formulaire d'une fiche détection. 
La modification principale consiste à remplacer les boucles JavaScript/AlpineJS par des balises de template Django (`for`).
Seule deux listes sont gardées (`structuresPreleveurs` et `sitesInspections`) car utilisées pour afficher le libellé/nom à partir de l'id (cf. `sv/static/sv/fichedetection_form.js`)
Remplacement des boucles JavaScript/AlpineJS par des balises de template Django pour :
* [`sv/templates/sv/_fichedetection_form__lieux_form.html`](diffhunk://#diff-c39b37f9b81d89db0607193cb0d181005e6a15813df26bcaa926c94b292a20a3L90-R101): `types_etablissement` et `positions_chaine_distribution`
* …

Supprime listes déroulantes JS par template django (formulaire fiche détection)

---

conftest.py
sv/tests/test_contact_add.py
sv/tests/test_fiche_detection_message.py
sv/tests/test_fichedetection_form.py
sv/tests/test_fichedetection_search.py
sv/tests/test_fichedetection_update.py

Permet de factoriser dans les tests les méthodes de sélection d'une option avec ChoiceJS. Cela permet de s'assurer que tous les tests utilisent `timeout=2_000` pour attendre que le sélecteur soit disponible.
Je n'ai jamais le problème de sélecteur en local avec n=auto (16 sur ma configuration), mais j'arrive a reproduire le problème avec n=4 qui correspond à la configuration de la CI.

Factoriser la sélection d'une option avec ChoiceJS

---

core/mixins.py
sv/models.py
sv/templates/sv/fichedetection_detail.html
sv/templates/sv/fichedetection_list.html
sv/tests/test_fichedetection_ac_notification.py

- Ajout de l'icône sur la vue de liste si la fiche est déclarée à l'AC
- Empecher de notifier l'AC sur une fiche en brouillon
Fixes https://github.com/betagouv/seves/issues/296

Améliorer la notification à l'AC

---

sv/managers.py
sv/tests/test_fichedetection_list_performances.py
sv/views.py

Avec toutes les FK depuis le modèle fiche détection beaucoup de queries étaient faistes vers la base de données.

Améliorer les performances de la vue de liste

---

sv/tests/test_fichedetection_create.py
sv/tests/test_fichedetection_update.py
sv/views.py

Permet de créer ou de modifier un lieu sans commune (et donc sans département et code INSEE).

Corriger la saisie d'un lieu sans commune

---

sv/api_views.py
sv/static/sv/fichedetection_form.css
sv/static/sv/fichedetection_form.js
sv/templates/sv/_fichedetection_form__prelevements_form.html
sv/tests/test_api_views.py
sv/tests/test_fichedetection_update.py
sv/urls.py
sv/views.py

Ce commit va permettre de choisir l'espèce de l'échantillon dans une liste déroulante avec recherche / complétion.
L'ajout de ChoiceJs sur le champ ne suffit pas car la librairie mets alors plusieurs secondes a initialiser le champ et le rendre réellement interactif.
J'ai du ajouter une petite API qui permet une recherche simple pour contourner ce problème. La page charge plus rapidement car pas de liste d'option a générer en HTML et est aussi interactive rapidement (très peu de JS a exécuter pour la liste déroulante).
Fixes #293

Permettre de choisir l'espèce dans une liste

---

core/templates/core/_contacts.html
core/templates/core/_modale_edition_document.html
core/templates/core/_modale_suppression_contact.html
core/templates/core/_modale_suppression_document.html
sv/templates/sv/fichedetection_detail.html

Voir ticket #161, le but est de rendre le tout plus cohérent, le bloc commun demande juste un objet de type fiche qui possède quelques méthodes / attributs (.pk, get_absolute_url, etc.).

Simplifier l'inclusion du template de bloc commun

---

sv/tests/test_fichedetection_performances.py
sv/views.py

Ce commit améliore les performances de la vue de détails d'une fiche détection quand les objets sont remplis avec toutes les foreign keys (ajout du fill optionnal dans les tests).
Avant les modifications dans la vue les tests avec fill_optional faisaient 20 et 34 requetes (lieux et prélévements respectivement).

Améliorer les performances de la vue de détails

---

sv/templates/sv/fichedetection_form.html
sv/tests/test_fichedetection_create.py
sv/tests/test_fichedetection_form.py

Ce commit permet de rendre plus explicite au niveau de l'interface le besoin d'avoir un lieu avant de pouvoir ajouter un prélèvement.
- Ajout du bouton grisé (disabled) tant qu'aucun lieu n'a été ajouté afin d'améliorer la découvrabilité de l'interface.
- Ajout d'un message explicite qui permet de débloquer la création de prélèvement via l'ajout d'un Lieu.
Fixes  #341

Rendre plus clair le besoin de lieu pour un prélèvement

---

core/forms.py
sv/filters.py
sv/static/sv/fichedetection_list.css
sv/static/sv/fichedetection_list.js
sv/templates/sv/fichedetection_list.html
sv/tests/test_fichedetection_list_performances.py
sv/tests/test_fichedetection_search.py
sv/views.py

Ce commit permet d'utiliser Django Filters dans la rechercher des fiches détection afin de rendre plus simple la mise en place de la recherche sur les fiches Zone delimitées.

Utiliser Django Filters pour la recherche de fiche

---

conftest.py

Par exemple:
```
FAILED sv/tests/test_fichedetection_form.py::test_add_lieu_form_is_empty_after_edit - playwright._impl._errors.Error: Locator.fill: Error: Element is not an <input>, <textarea> or [contenteditable] element
```

Tenter de corriger la CI

---

sv/managers.py
sv/tests/test_fichedetection_search.py
sv/views.py

Le but de ce commit est de s'assurer que l'ordre est bien respecté sur la vue de liste des fiches détection. Ce n'était pas le cas a cause de la redéfinition de la méthode get_queryset sur la classe. J'en ai profité pour préciser l'ordre précis sur le modèle Numéro afin d'éviter un ordre implicite qui ne corredpond pas a ce qui était voulu.

Corrige l'ordre de la liste de fiche detection

---

sv/export.py
sv/managers.py
sv/tests/test_export.py
sv/views.py

Le but de ce commit est de limiter les fiches exportables par un utilisateur/utilisatrice donné à ce qui est effectivement visible dans l'outil. Ainsi la prise en compte des règles de visibilité empéche un agent de voir dans l'export des fiches qu'il ne verrait pas dans l'outil.
Au cours de mes tests je me suis rendu compte que l'export était relativement lent même pour une base relativement petite (~800 lignes dans le fichier CSV). J'ai optimisé et rendu les tests plus réalistes avec l'utilisation de _fill_optional.
Fixes #299

Limiter les résultats de l'export pour l'utilisateur

---

sv/forms.py
sv/models.py
sv/static/sv/fichedetection_detail.js
sv/templates/sv/_lienlibre_modal.html
sv/tests/test_fichedetection_liens.py
sv/tests/test_fichedetection_performances.py

Permet d'utiliser les liens libres entre les fiches zones et les fiche détection.
Ajout de la bibliothèque ChoicesJs pour permettre une recherche dans le champ de liste des fiches.
Fixes #295
En attente de la vue de détail d'une zone @alanzirek

Lier des fiches Zone et Détection

---

sv/tests/test_fichezonedelimitee_performances.py
sv/views.py

Utilisation d'un attribut de la classe comme "cache" local pour éviter de réaliser plusieurs fois l'opération. Sera d'autant plus utile que l'on réalise souvent get_object dans les mixins.

Améliorer les performances de la fiche zone

---

sv/tests/conftest.py
sv/tests/test_fichedetection_form.py

Cette PR : 
- Refactorise la fixture `fill_commune` pour utiliser `choice_js_fill`, éliminant ainsi la duplication de code pour la manipulation des champs Choices.js. Maintien de la même interface pour `fill_commune`
- Utilisation de fixture choice_js_fill dans la fonction _add_new_lieu.
- Tente de corriger certains tests qui fail sur la CI. Exemple : 
```
FAILED sv/tests/test_fichedetection_form.py::test_add_lieu_form_is_empty_after_close_edit_form_with_close_btn_without_save - playwright._impl._errors.Error: Locator.fill: Error: Element is not an <input>, <textarea> or [contenteditable] element
```

Réutiliser choice_js_fill (fixture pytest) + corriger fail CI

---

cron.json

Modification du cron d'envoi des emails (exécution toutes les 10 minutes) pour respecter la contrainte du Scheduler Scalingo.
> Limitations
> The smallest scheduling interval is set to 10 minutes. For example, the Scalingo Scheduler won’t let you set up a task to run every 5 minutes (the deployment will fail).
https://doc.scalingo.com/platform/app/task-scheduling/scalingo-scheduler

Modification du cron d'envoi des emails

---

sv/templates/sv/fichedetection_form.html
sv/tests/test_utils.py

Sur le formulaire de la fiche détection, modification du libellé pour les boutons permettant d'ajouter un lieu et ajouter un prélèvement.

Modification libellé boutons sur formulaire fiche détection

---

core/templates/core/_contacts.html

Supprime le retour à la ligne lors de l'affichage des structures dans la liste des contacts (cf. https://github.com/betagouv/seves/issues/275#issuecomment-2386267853)

Supprime retour à la ligne avant affichage des structures sur liste contacts

---

sv/tests/test_fichedetection_create.py
sv/views.py

Cette PR corrige l'erreur lors de l'ajout de plusieurs prélèvements dans une fiche détection (liaison entre les lieux et les prélèvements).

Fix erreur lors de l'ajout de plusieurs prélèvements dans une fiche détection

---

sv/constants.py
sv/static/sv/fichedetection_form.js
sv/templates/sv/fichedetection_form.html
sv/tests/conftest.py
sv/tests/test_fichedetection_create.py
sv/views.py

Ce commit va permettre dans certains cas (les plus courants) de sélectionner le statut réglementaire associé à un organisme nuisible (via son code OEPP).
Introduction d'un mapping dans le code qui servira aussi pour la reprise d'historique.

Permettre de sélectionner automatiquement le statut

---

sv/templates/sv/fichedetection_form.html
sv/tests/test_fichedetection_create.py
sv/tests/test_fichedetection_update.py
sv/views.py

Le but de ce commit est de ne permettre l'édition des numéros RASFF et Europhyt que par l'administration centrale que cela soit pour la création ou la modification de fiches détection.
On masque les champs dans le HTML pour ne pas permettre l'édition, mais on ajoute aussi une sécurité backend pour éviter qu'une personne puisse tout de même éditer les valeurs sans en avoir le droit.
Dans les tests j'utilise `evaluate` à la place de `force=True` pour deux raisons:
- Cela correspond mieux au cas d'usage que l'on veut simuler (afficher la case puis la remplir)
- L'option force ne semble pas déclencher l'exécution du JavaScript au niveau d'AlpineJs et les nouvelles valeurs ne sont donc pas envoyées.
Fixes #403

Permettre l'édition RASFF et Europhyt uniquement par l'AC

---

sv/static/sv/fiche_list.css
sv/templates/sv/fiche_list.html

Améliore le tableau de liste sur des petits écrans d'ordinateur. L'affichage est toujours mauvais quand la largeur est faible mais améliore la situation dans la zone 1000px à 1400px de large.

Améliorer le rendu du tableau sur petit écran

---

sv/static/sv/fichedetection_form.js
sv/tests/test_fichedetection_create.py

Réinitialise le status réglementaire quand un changement d'organisme nuisible est fait afin d'éviter de laisser une valeur fausse.

Réinitialiser le status quand changement d'ON

---

sv/tests/test_fichedetection_create.py

Etre sur que l'on utilise toujours l'ID du bon objet pour la comparaison

Corriger les tests sur le status réglementaire

---

sv/static/sv/fichedetection_detail.css
sv/templates/sv/_fichedetection_form__lieux_form.html
sv/templates/sv/fichedetection_detail_lieu.html
sv/views.py

Affiche le nom et pas le libellé, deplace l'affichage dans la bonne section.

Corriger l'affichage des sites d'inspection

---

sv/static/sv/fichedetection_form.css
sv/templates/sv/fichedetection_form.html

Modification de l'emplacement du champ végétaux infestés sur le formulaire de la fiche détection.
Réajustement de la hauteur des bloc lieu et prélèvement : 
Avant:
Après:

Modification de l'emplacement du champ végétaux infestés sur le formulaire de la fiche détection

---

account/templatetags/groups.py

Dans le commit `6f6fd6c6ab9c023d244f01697bcb72ab30f43ad8` nous avons ajouté le groupe dans une migration, ce qui fait que le groupe est présent lors des tests.
Cela ajoutait une requête SQL dans les tests de performances en biaisant le résultat (le code que l'on veut tester ne fait pas plus de requêtes mais la page au global oui).
Reécriture du template tags pour qu'il ne fasse plus qu'une seule requête, peut importe la configuration des groupes. Idéalement il faudrait déplacer ça dans un contexte processors, si nous utilisons cette logique a plusieurs endroits.

Corriger le nombre de requêtes pour accéder aux groupes

---

core/forms.py
core/models.py
core/templates/core/message_detail.html
sv/tests/test_fiches_message.py

Ce commit s'assure que tous les affichages de contacts respectent la même règle d'affichage.
- Normalisation des méthodes utilisées
- Ajout d'un test
Fixes #436

Normaliser l'affichage des contacts

---

sv/forms.py
sv/tests/test_fichezonedelimitee_update.py
sv/views.py

Ce commit empêche de lier une fiche zone a elle-même via les liens libres.
- Retire la fiche en cours de modification de la liste de choix autorisés
- Retourne une erreur de validation si cela venait tout de même à se produire
Fixes SEVES-11

Empêcher de lier une fiche Zone a elle-même

---

sv/templates/sv/fichedetection_detail_lieu.html
sv/tests/test_fichedetection_detail.py

Quand un lieu est un établissement le nom de l'établissement n'était jamais affiché dans la modale de visualisation du lieu sur la page détails de la fiche détection.
Ajout de test pour vérifier la modale dans le cas le plus complet.
Fixes #420

Corrige l'affichage du nom de l'établissement

---

conftest.py
core/forms.py
core/managers.py
core/models.py
core/tests/test_managers.py
sv/tests/test_fichedetection_create.py
sv/tests/test_fiches_contact_add.py
sv/tests/test_fiches_message.py
sv/tests/test_fiches_structure_add.py

On peut écrire uniquement a:
- un contact dont l'utilisateur qui est actif et qui a un email
- une structure qui a un mail
Cela s'applique dans l'interface de rédaction des messages (fil de suivi) ou dans l'interface d'ajout de structures ou de contacts.
Fixes #438

Empêcher d'écrire aux utilisateurs inactifs

---

sv/forms.py
sv/managers.py
sv/tests/test_fichezonedelimitee_create.py
sv/tests/test_fichezonedelimitee_update.py

Cette PR empêche l'ajout d'une fiche détection brouillon en zone infestée ou hors zone infestée dans le formulaire de création et modification d'une fiche zone délimitée.
- ajout d'une méthode dans le manager permettant d'exclure les fiches détection ayant la visibilité brouillon
- modification du queryset pour le champ détections dans hors zone infestée et zone infestée
- ajout de tests pour zone infestée et hors zone infestée
- modification de la visibilité à local dans certains tests car ne passés plus

Fiche zone délimitée: empêche l'ajout d'une fiche détection brouillon en zone infestée ou hors zone infestée

---

sv/display.py
sv/tests/test_fiches_search.py

Cette PR permet d'afficher `non attribué` si pas de numéro de fiche dans la liste des fiches.
Liée à https://github.com/betagouv/seves/issues/408

Dans la liste des fiches (détection et zone), affiche non attribué si pas de numéro de fiche

---

sv/static/sv/fichedetection_form.js
sv/templates/sv/fichedetection_form.html
sv/tests/test_fichedetection_update.py
sv/views.py

Cette PR permet d'afficher le boutons `enregistrer brouillon` et `publier` sur le formulaire de modification d'une fiche détection si la fiche est en visibilité `brouillon`.
cf. commit ee523ccbfb8d070f9133b2f2187ed8aca3db69a5
J'ai aussi supprimé l'affichage du numéro de fiche sur le formulaire de modification d'une fiche détection en visibilité brouillon car actuellement None est affiché (car pas de numéro de fiche en brouillon). 
cf. commit 2b6b7e229b38cc44973a9bc9cb084480ba4b0149
Liée à https://github.com/betagouv/seves/issues/408

Afficher que boutons enregistrer brouillon et publier sur formulaire de modification fiche détection

---

core/forms.py
core/mixins.py
sv/templates/sv/fichedetection_detail.html
sv/tests/test_fichedetection_performances.py
sv/tests/test_fichedetection_visibilite_access.py
sv/tests/test_fichedetection_visibilite_update.py
sv/views.py

Cette PR ajoute un bouton `Publier` sur la page de détail d'une fiche détection permettant de passer la visibilité de la fiche de `brouillon` à `local`.
J'ai modifié le form `VisibiliteUpdateBaseForm` pour prendre en compte le fait que la visibilité peut aussi être modifié via le bouton Publier.
Cela à pour conséquence l'augmentation du nombre de requête (+1) car un autre form est injecté dans le context (`publier_form`).
À noter que le changement de visibilité pour une fiche brouillon via la modale va disparaitre dans PR #483.
Donc à terme (dans la PR #483), il n'y aura qu'un form d'injecté dans le context pour le changement de visibilité (`publier_form`) :  https://github.com/betagouv/seves/blob/c80d5307e42ff2bbc0e1f44caa93b1edfd328b1c/sv/views.py#L138-L141
J'ai ajouté un mixin …

Ajout du bouton publier sur la page de détail d'une fiche détection.

---

sv/forms.py
sv/managers.py
sv/tests/test_fichedetection_create.py
sv/tests/test_fichedetection_form.py
sv/tests/test_fichedetection_update.py
sv/tests/test_fichezonedelimitee_create.py
sv/tests/test_fichezonedelimitee_update.py
sv/views.py

Cette PR permet de ne pas pouvoir ajouter des fiches brouillon dans les liens libres
- ajout du filtre pour le formulaire de création et de modification pour les fiches détection et fiches zones délimitées
- ajout des tests pour vérifier que le champ Liens libres ne contient pas de fiche brouillon

Liens libres : empêche l'ajout de fiche brouillon

---

seves/context_processors.py
seves/settings.py
sv/templates/sv/_fichedetection_form__lieux_form.html
sv/templates/sv/_fichedetection_form__prelevements_form.html
sv/templates/sv/fichedetection_form.html
sv/tests/conftest.py
sv/tests/test_fichedetection_create.py
sv/tests/test_fichedetection_update.py

iAjout d'un context processor et d'un setting Django pour s'assurer que toutes les listes déroulantes (select) ont la même valeur vide de proposée à l'utilisateur.
Fixes #456

Uniformiser et expliciter les valeurs vides des selects

---

core/management/commands/import_contacts.py
core/tests/test_import_contacts.py

WIP: il manque l'ajout de test pour l'erreur IntegrityError générée
Cette PR : 
- Corrige l'erreur IntegrityError si plusieurs imports à la suite sont effectués.
Lorsque qu'un import est effectué, qu'un user est activé, un second import est effectué, il y une erreur de type IntegrityError. Pour corriger cette erreur, remplacement de get_or_create par update_or_create.
- Ajoute le niveau 1 dans le libellé de la structure si le niveau 2 est vide.

Fix erreur si plusieurs imports à la suite + libellé structure

---

core/mixins.py
core/views.py
sv/templates/sv/_detection_action_navigation.html
sv/templates/sv/fichedetection_detail.html
sv/tests/test_fichedetection_ac_notification.py
sv/tests/test_fichedetection_detail.py
sv/tests/test_fichedetection_update.py
sv/tests/test_fichedetection_visibilite_update.py
sv/views.py

Cette PR permet de restreindre le nombre d'actions possibles lors de la consultation d'une fiche détection en brouillon.
Aussi, elle supprime l'accès à la modal de changement de visibilité.
Lors de la consultation d'une fiche détection en brouillon, la seule action accessible est supprimer. 
La restriction effectuée côté frond, dans le template `sv/templates/sv/_detection_action_navigation.html`.
Pour le contrôle côté serveur, j'ai ajouté le mixin `PreventActionIfVisibiliteBrouillonMixin `.
Il a été appliqué aux view correspondantes aux actions : déclarer à l'AC et ajouter une zone.
L'accès à la modale étant supprimé, l'ajout d'un bouton publier a été fait dans la PR #481.

Restriction des actions lors de la consultation d'une fiche détection brouillon

---

core/mixins.py
sv/tests/test_fichedetection_ac_notification.py

Le problème initial est que `notify_message(message)` dans la méthode `notify_ac()` raise une exception de type `ValidationError - 'recipients:  is not a valid email address'` si le mail du contact MUS et/ou BSV est vide.
Donc, la sauvegarde du booléen `is_ac_notified` via `self.save()` n'est jamais effectuée.
De plus, un objet de type `Message` est créé en base alors qu'il y a eu un problème lors de l'envoi.
Pour garantir une cohérence en base des différents objets impliqués : 
- gérer `notify_message(message)` dans un try et sauvegarder le message uniquement si pas d'erreur dans l'envoi de la notif
- ajout d'une transaction atomique pour la sauvegarde de la fiche et du message

Fix erreur notification AC si adresses mails de la MUS et/ou BSV sont vides

---

core/mixins.py
core/views.py
sv/templates/sv/fichedetection_detail.html
sv/tests/test_fichedetection_detail.py
sv/tests/test_fichedetection_performances.py
sv/tests/test_fiches_contact_add.py
sv/tests/test_fiches_documents.py
sv/tests/test_fiches_message.py
sv/tests/test_fiches_structure_add.py
sv/views.py

Cette PR permet de masquer le bloc de suivi si la fiche détection est en visibilité brouillon.
Liée à https://github.com/betagouv/seves/issues/408
- modification du template detail de la fiche détection pour masquer le bloc de suivi et les modales utilisées dans celui-ci.
- ajout de tests bloc de suivi masqué si brouillon et affiché si local ou national
- Application du mixin `PreventActionIfVisibiliteBrouillonMixin` dans les vues du bloc de suivi
- ajout de tests pour vérifier que les requêtes HTTP sur les différentes routes du bloc de suivi soient refusées si la fiche est en brouillon
Renommage de la méthode `get_object` en `get_fiche_object` dans `PreventActionIfVisibiliteBrouillonMixin`.
Le renommage était nécessaire car avec `get_object`, il y avait un conflit avec la méthode du même …

Masque le bloc de suivi si la fiche détection est en visibilité brouillon

---

sv/static/sv/fichedetection_form.js
sv/tests/test_fichedetection_create.py

Cette PR empêche les soumissions multiples du formulaire de la fiche détection.
Lors de clics rapides ou répétés sur le bouton "Enregistre le brouillon" ou "Publier", plusieurs requêtes sont envoyées au serveur avant que la première ne soit terminée. Cela se produit parce que chaque clic déclenche une nouvelle exécution de la fonction JavaScript permettant de sauvegarder la fiche détection en base, sans mécanisme natif pour limiter ces appels simultanés.
Pour résoudre ce problème, les boutons "Enregistre le brouillon" et "Publier" sont désactivés après le premier clic. Cela garantit qu'une seule requête est envoyée par soumission, tout en réactivant le bouton en cas de validation échouée ou d'erreur de requête.

Empêcher les soumissions multiples du formulaire de la fiche détection

---

core/static/core/message_form.js
sv/tests/test_fiches_message.py

Passage à 500 du nombre de résultat lors d'une recherche dans les champs Destinataire et Copie lors de la rédaction d'un nouveau message. 
Par défaut, choiceJS limite le nombre de résultat à 4 lors d'une recherche dans un champ (https://github.com/Choices-js/Choices?tab=readme-ov-file#searchresultlimit-4)

Augmente le nombre de résultat dans le champ Destinataires et Copie d'un nouveau message

---

sv/static/sv/fichedetection_form.js
sv/templates/sv/_fichedetection_form__lieux_form.html
sv/tests/test_fichedetection_form.py
sv/tests/test_utils.py

Cette PR supprime le champ lambert93 dans le formulaire d'ajout/modification d'un Lieu (cf. fiche détection).
Oubli de la PR #503

Suppression du champ lambert93 dans le formulaire

---

sv/tests/test_fiches_search.py

On réutilise la même fiche pour ne pas avoir a gérer le cas où le nouveau numéro est plus grand ou plus petit que l'ancien (ce qui change l'ordre dans le tableau et donc le sélecteur a utiliser).

Fiabiliser les tests sur la liste de fiches

---

sv/templates/sv/fichezonedelimitee_detail.html
sv/tests/test_fichedetection_detail.py
sv/tests/test_fiches_bloc_suivi.py

Cette PR permet de masquer le bloc de suivi si la fiche zone délimitée est en visibilité brouillon.
- modification du template detail de la fiche zone pour masquer le bloc de suivi.
- ajout des tests pour fiche zone et regroupés dans`sv/tests/test_fiches_bloc_suivi.py` (uniquement ceux concernant les tests de présence du bloc de suivi dans l'UI).
dans la PR #479 :
- toutes les protections des routes ont déjà été effectuées dans `core/views.py`, y compris pour la fiche zone délimitée.
- les tests permettant de s'assurer de la protection des routes pour la fiche zone délimitée ont été faits via la fixture `fiche_variable`.

Masque le bloc de suivi si la fiche zone délimitée est en visibilité brouillon

---

sv/filters.py
sv/tests/test_fiches_search.py

Cette PR corrige le bug suivant : 
> Si dans une fiche detection, j'ai 2 lieux situés dans la même region, quand j'effectue un filtre sur cette région, la fiche détection apparait deux fois dans les résultats.
Ticket Notion : https://www.notion.so/incubateur-masa/Suppression-des-doublons-dans-les-r-sultats-de-filtrage-par-r-gion-des-fiches-d-tection-153de24614be8043ad0dd10991737371?pvs=4

Suppression des doublons dans les résultats de filtrage par région des fiches détection

---

sv/models.py
sv/templates/sv/fichezonedelimitee_form.html
sv/tests/test_fichedetection_update.py

Cette PR corrige le fait que la visibilité sur le formulaire de modification de la fiche zone délimitée était toujours affichée `brouillon`.
J'ai aussi ajouté `get_update_url` et refactoré les tests en conséquence.
Issue Notion : https://www.notion.so/incubateur-masa/Visibilit-de-la-fiche-zone-toujours-brouillon-d-affich-e-154de24614be8030acebd4b6e9b459c9?pvs=4

Correction affichage visibilité sur le formulaire de modification de la fiche zone délimitée

---

sv/templates/sv/_zone_action_navigation.html
sv/templates/sv/fichezonedelimitee_detail.html
sv/tests/test_fichezonedelimite_visibilite_update.py
sv/tests/test_fichezonedelimitee_detail_performances.py
sv/views.py

Sur la page de consultation d'une fiche zone délimitée en visibilité brouillon :
- ajout du bouton publier, permettant de passer la visibilité à 'local'
- suppression de l'accès au formulaire de modification de la visibilité (modale) via le menu +Actions
J'ai aussi : 
- modifier les tests `test_cannot_update_fiche_zone_delimitee_visibilite_by_other_structures ` et `test_agent_in_structure_createur_cannot_update_fiche_zone_delimitee_visibilite ` car faux positif.
- supprimé la méthode `get_form_kwargs` dans `FicheDetectionVisibiliteUpdateView ` car pas utile.

Ajout bouton publier et retrait modale visibilité sur page consultation fiche zone délimitée brouillon

---

core/templates/core/login.html
seves/middlewares.py

En cas de demande de connection suite à la consultation d'une URL précise (une fiche par exemple), redirigier automatiquement le navigateur sur la page de la requête initiale.
- Simplification du middleware pour utiliser une vue déjà présente dans Django et qui gère le paramètre next
- Ajout du paramètre dans le template
- Fonctionne sans autre paramètrage car Django OIDC respecte le champ next pour la redirection (https://mozilla-django-oidc.readthedocs.io/en/stable/settings.html#OIDC_REDIRECT_FIELD_NAME)

Rediriger vers la bonne page après la connection

---

sv/tests/test_notifications.py

- Extrait la création et notification des messages dans une fonction utilitaire `(create_message_and_notify`)
- Crée une fonction utilitaire pour les assertions communes sur les mails (`assert_mail_common`)
- Supprime la duplication de code dans les tests
- Améliore la lisibilité des tests

Factoriser les tests de notification

---

sv/static/sv/fichedetection_lieux_form.js
sv/tests/test_fichedetection_form.py

Sur le formulaire de la fiche détection, si je créé un lieu et que je le supprime, le message d'information `"pour ajouter un prélèvement vous devez..."` ne s'affiche plus.
Suppression du `return` lorsqu'il y a pas de lieu car l'appel `showOrHidePrelevementUI()` n'était pas exécuté.

Corrige interface bloc prélèvement quand pas de lieux

---

sv/display.py
sv/managers.py
sv/templates/sv/_fichedetection_synthese.html
sv/templates/sv/fichedetection_detail.html
sv/tests/test_fichedetection_detail.py
sv/tests/test_fichedetection_list.py
sv/tests/test_fichedetection_performances.py
sv/views.py

- ajout d'une liste des lieux sans commune renseignée dans le context du détail de la fiche détection (cf. `FicheDetectionDetailView`)
- dans la vue liste des fiches détection, suppression des lieux qui n'ont pas de commune renseignée dans la requête
- ajout de nc. sur la carte d'un lieu si pas de commune renseignée
Ticket Notion : https://www.notion.so/incubateur-masa/Enlever-le-commune-0-en-vue-synth-se-150de24614be8013be43c9e88dd75a7c?pvs=4

Modification affichage Commune sur vue synthèse et liste fiches détection

---

sv/templates/sv/fichedetection_form.html
sv/tests/test_fichedetection_create.py
sv/tests/test_fichedetection_update.py

Cette PR supprime le doublon "Modification de la fiche..." dans le formulaire de modification d'une fiche détection.
- supprime le doublon "Modification de la fiche..." dans le template
- utilisation de `get_by_role` pour tester les titres pour vérifier l'exactitude du texte (via paramètre `exact=True`)
- ajoute un test pour le titre de la page du formulaire de modification pour une fiche détection brouillon
Ticket Notion : https://www.notion.so/incubateur-masa/Ticket-de-recette-158de24614be80d488c2d9b9f2228cd7?pvs=4

Corrige le titre de la page du formulaire de modification d'une fiche détection

---

sv/forms.py
sv/static/sv/fichedetection_form.css

Dans le formulaire d'ajout/modification d'un lieu d'une fiche détection, pour le champ `activite_etablissement` : 
- ajout d'une textarea pour augmenter le nombre de ligne
- modification du label
Ticket Notion : https://www.notion.so/incubateur-masa/Case-activit-s-d-un-tablissement-revoir-150de24614be80b4ada2f23e95284b3a?pvs=4

Modification du champ Activité établissement dans le formulaire Lieu d'une fiche détection

---

sv/static/sv/fiche_list.js
sv/tests/test_fiches_search.py

Au chargement de la page désactiver le filtre des régions si jamais l'utilisateur est sur une liste de fiche zone.

Empêcher de rechercher par région sur la liste de zone

---

core/mixins.py
core/views.py
sv/models.py
sv/tests/test_fichedetection_soft_delete.py

Ce commit empêche un(e) utilisateur(trice) de supprimer une fiche / un objet si cela n'est pas explicitement autorisé au niveau de l'objet. Cela empêche en particulier de supprimer une fiche détection auquelle l'utilisateur n'aurait pas accès en créant la bonne requête HTTP de toute pièce.

Empêcher de supprimer une fiche sans droit de lecture

---

sv/forms.py
sv/tests/test_fichezonedelimitee_create.py

Retire complétement la notion de choix de rattachement qui n'est plus utilisé depuis le commit précédent sur l'introduction de l'événement. Corrige les tests et retire complétement un test qui n'a plus de sens (ce comportement est déjà testé par
test_fiche_detection_are_filtered_by_evenement_of_fiche_detection)

Retirer la notion de rattachement

---

sv/templates/sv/fichezonedelimitee_form.html
sv/tests/test_fichezonedelimitee_create.py

Corrige le lien d'annnulation sur la page de création de fiche zone delimitée. Ajout d'un test.

Corriger le lien d'annulation sur le form de zone

---

sv/static/sv/evenement_details.css
sv/templates/sv/evenement_detail.html
sv/tests/test_evenement_details.py

Au sein d'un même événémenent, désactiver le bouton de création de Zone si une zone existe déjà. La vérification est déjà faite côté back et amenait de toute façon sur une page d'erreur.

Empêcher de créer plusieurs fois une zone

---

sv/forms.py
sv/static/sv/fichedetection_form.css
sv/static/sv/fichedetection_lieux_form.js
sv/templates/sv/_fichedetection_form__lieux_modal.html
sv/templates/sv/fichedetection_detail_lieu.html
sv/tests/test_fichedetection_form.py

Dans le formulaire d'un lieu dans une fiche détection ajout : 
-  d'une restriction sur la taille max du descripteur "Description de l’activité" côté front (ajout de maxlength dans l'input)
- d'un compteur de caractères visuel permettant à l'utilisateur de suivre en temps réel le nombre de caractères restants lors de la saisie.

Ajout max length sur l'input du champ Description de l’activité (Lieu) + compteur de caractères

---

core/templates/core/_carte_resume_document.html
core/templates/core/_documents.html

Affichage d'un nombre de document dans la liste en fonction de la taille de l'écran : 
- Sur mobile (breakpoint DSFR xs → < 576px) : 1 carte par ligne
- Sur petit écran (breakpoint DSFR sm → ≥ 576px) : 2 cartes par ligne
- Sur écran moyen (breakpoint DSFR md → ≥ 768px) : 3 cartes par ligne
- Sur grand écran (breakpoint DSFR lg et plus → lg : ≥ 992px) : 4 cartes par ligne

Améliore l'affichage des cartes documents

---

sv/templates/sv/_cloturer_modal.html
sv/templates/sv/_evenement_action_navigation.html
sv/tests/test_evenement_etats.py
sv/urls.py
sv/views.py

Corrige le vocabulaire utilisé pour coller au modèle fiche. Remet en place un test existant avant le changement de l'événement.

Améliorer l'interface de cloture d'un événement

---

sv/tests/test_fichedetection_update.py
sv/view_mixins.py

Lors de la modification d'une fiche de détection, une erreur 500 apparaît dans le cas suivant :
- Je modifie une fiche
- Je supprime un prélèvement
- Je supprime son lieu associé
- Je sauvegarde les modifications
L'erreur se produit car nous essayons de supprimer un prélèvement qui n'existe plus (il a déjà été supprimé au moment de la suppression du lieu à cause de la cascade).
Ajout d'un try/except dans la méthode `_save_prelevement_if_not_empty` du `WithPrelevementHandlingMixin` pour gérer deux scénarios de suppression :
1. L'utilisateur supprime uniquement un prélèvement (le lieu n'est pas supprimé)
2. L'utilisateur supprime un lieu, ce qui entraîne la suppression en cascade de ses prélèvements
Lorsque le prélèvement a déjà été supprimé via la cascade, nous ignorons l'exception …

Correction de l'erreur 500 lors de la suppression d'un lieu et d'un prélèvement lié

---

core/mixins.py
core/templates/core/_carte_resume_contact.html
core/templates/core/_contacts.html
sv/tests/test_evenement_contacts_list.py
sv/tests/test_evenement_etats.py

Cette PR permet d'afficher le badge "fin de suivi" pour les contacts de type agent dont la structure est en fin de suivi
Optimisation :
- Récupération des ids de structures en fin de suivi
- Pour is_in_fin_suivi : comparaison par ids au lieu d'objets pour de meilleures performances
- Cache de l'objet principal dans le mixin pour éviter les appels multiples à get_object()

Affiche fin de suivi pour les contacts (agents) d’une structure en fin de suivi

---

sv/static/sv/evenement_details.js
sv/templates/sv/evenement_detail.html
sv/tests/test_evenement_details.py

Cette PR ajoute la possibilité de basculer entre une vue détaillée et une vue synthétique sur le détail de la fiche évènement.

Gestion du swith détail/synthèse sur la page détail de la fiche évènement

---

sv/forms.py
sv/static/sv/fichedetection_lieux_form.js
sv/tests/test_fichedetection_update.py

Fix: dans le formulaire de modification d’un lieu, lorsqu’il y a une commune enregistrée pour un lieu, elle ne s’affiche pas dans la carte et dans le champ lors de l’ouverture de la modal

Fix affichage commune dans la carte et modal du formulaire Lieu (fiche détection)

---

sv/tests/test_utils.py

Correction d'un test instable qui échouait en CI uniquement. Le test `test_fichezonedelimitee_update_without_zone_infestee_form_submit` échouait de manière aléatoire lorsque la factory générait `HECTARE` comme unité de surface via `FuzzyChoice`.
La méthode `_select_unite_surface_tampon_totale` ne gérait pas le cas où l'unité de surface était en hectares dans son pattern matching, alors que cette valeur pouvait être générée par la factory.
Ajout du cas `HECTARE` dans le pattern matching de la méthode `_select_unite_surface_tampon_totale`.

Ajoute la gestion du cas HECTARE dans la sélection des unités de surface (fix un test qui fail en CI)

---

sv/templates/sv/fichedetection_detail_prelevement.html
sv/tests/test_fichedetection_detail.py

Reprise de la modale de visualisation d'un prélèvement pour que les champs soient dans l’ordre du formulaire et avec les mêmes noms.
J'ai supprimé le test `test_prelevement_non_officiel_details` car redondant avec `test_prelevement_details`.
Utilisation des factory dans `test_prelevement_non_officiel_details_second_prelevement`.

Reprise de la modale de visualisation d'un prélèvement

---

core/factories.py

Ajoute `UserFactory`, `AgentFactory`, et les factories de contacts (`ContactAgentFactory`, `ContactStructureFactory`) pour simplifier la création des objets de test.
J'ai privilégié une séparation explicite en deux factories distinctes (`ContactAgentFactory` et `ContactStructureFactory`) plutôt qu'une factory avec traits pour une meilleure lisibilité et pour refléter la contrainte métier qu'un contact doit être soit lié à un agent, soit à une structure.

Ajoute les factories pour les tests des contacts

---

sv/tests/test_evenement_etats.py
sv/tests/test_fichedetection_update.py
sv/tests/test_fichezonedelimitee_update_performance.py

Retrait des derniers décorateurs "skip" afin que tous les tests soient lancés.

Réintégrer des tests dans la suite de tests

---

core/versions.py
sv/models/evenements.py
sv/models/fiches_detection.py
sv/models/fiches_zone_delimitee.py
sv/signals.py
sv/templates/sv/evenement_detail.html
sv/tests/test_evenement_details.py
sv/tests/test_evenement_performance_details.py
sv/tests/test_models.py
sv/views.py

Permet de suivre les modifications d'un objets et des objets liés pour l'événement et la fiche zone. Affiche la dernière modification sur la page de l'événement.

Suivre les modifications sur l'événement de la fiche Zone

---

core/factories.py
core/models.py
core/views.py
sv/tests/test_evenement_contact_add.py

Sur une fiche évènement, lorsqu'un agent est ajouté comme contact d'une fiche, sa structure est automatiquement ajouté à la liste des contacts.
- Ajout de la méthode `get_structure_contact()` sur le modèle `Contact`
- Modification du `form_valid()` pour ajouter le contact structure automatiquement
- Ajout de tests pour vérifier :
- L'ajout du contact structure lors de l'ajout d'un contact agent (`test_add_agent_contact_adds_structure_contact`)
- La non-duplication du contact structure lors de l'ajout de plusieurs agents de la même structure (`test_add_multiple_agent_contacts_adds_structure_contact_once`)
- Ajout du formatage français des numéros de téléphone dans `AgentFactory` pour générer des numéros au format français plutôt que des séquences arbitraires.

Ajout automatique de la structure lors de l'ajout d'un agent

---

sv/static/sv/evenement_details.js
sv/static/sv/view_manager.js
sv/templates/sv/evenement_detail.html
sv/tests/test_evenement_details.py

- Persistance du choix de vue pour chaque fiche événement via localStorage
- Restauration automatique du dernier mode de vue utilisé pour chaque fiche
- Mode détail par défaut pour les nouvelles fiches
- Test du mode par défaut (détail)
- Test de la persistance du choix pour chaque fiche
- Test de la conservation des préférences après navigation
- Test du rechargement de page
Le code a été réorganisé et encapsulé dans un module JS réutilisable (`ViewManager`) qui gère la logique de persistance et le changement de vue, avec une API publique réduite à l'initialisation.

Persistance du mode d'affichage (détail/synthèse) sur le détail de la fiche Évènement

---

sv/static/sv/evenement_details.css
sv/static/sv/evenement_details.js
sv/templates/sv/evenement_detail.html

Cette PR ajoute une mise en évidence visuelle du tag sélectionné dans la liste des détections :

Ajoute une mise en évidence visuelle du tag sélectionné dans la liste des détections

---

core/forms.py
core/templates/core/_dsfr_div.html
sv/filters.py
sv/static/sv/fiche_list.css
sv/static/sv/fiche_list.js
sv/templates/sv/fiche_list.html
sv/tests/test_fiches_search.py

- Déplacement des boutons de type de fiche pour libérer de la place et uniformiser le comportement avec les futurs domaines
- Pré-sélection d'un type de fiche et submit automatique en cas de changement
- Divers changement de style pour que les champs aillent à la ligne sur petits écrans
Concernant le test de vérification de l'auto-submit du form, je n'ai pas trouvé d'autre moyen de vérifier que la page avait été rechargée:
- J'ai essayé `expect_request` qui semble fonctionner uniquement pour les requêtes au sein de la page
- `wait_for_load_state` reste vrai même sans rechargement, probablement car le document est déjà dans l'état "loaded"
- Une autre solution aurait été d'ajouter un paramètre dans l'url et de vérifier sa disparition lors du rechargement
Ajout d'un mécanisme qui permet de …

Améliorer la vue de liste sur petits écrans

---

core/factories.py
core/forms.py
core/managers.py
sv/tests/test_evenement_structure_add.py

Ce commit permet de limiter l'ajout de structures au fil de suivi aux structures ayant au moins un utilisateur actif dans SEVES.

Limiter l'ajout de structure avec un user actif

---

sv/tests/test_fichedetection_create.py
sv/views.py

Corrige un bug dans la création de fiche détection où le formulaire échouait lors de la validation avec un événement existant. 
Le problème provenait du formulaire `EvenementForm` qui nécessitait les champs `organisme_nuisible` et `statut_reglementaire` même lors de la réutilisation d'un événement existant. 
La correction consiste à pré-remplir ces champs avec les valeurs de l'événement existant lors de la soumission du formulaire.

Correction bug lors de la création de fiche détection avec événement existant

---

core/views.py
sv/tests/test_evenement_message.py

Ce commit s'assure que les structures des agent(e)s destinataire et copies d'un message sont bien ajoutées en tant que contact dans la fiche.

S'assurer que les structures sont en contact

---

sv/factories.py
sv/tests/test_fichezonedelimitee_update.py
sv/views.py

Lors de la mise à jour d'une fiche zone délimitée liée à un événement en brouillon, une erreur `AttributeError` se produit car l'événement n'est pas accessible dans le formulaire pour obtenir le numéro.
Ajout de l'événement dans les données initiales (`initial`) de la vue `FicheZoneDelimiteeUpdateView`
- Vérifier qu'une fiche zone délimitée peut être mise à jour sans erreur avec un événement en brouillon -> `test_can_update_fiche_zone_if_evenement_brouillon`
- Ajout du champ `commentaire` dans la factory `FicheZoneFactory`

Corrige l'erreur lors de la mise à jour d'une fiche zone délimitée

---

sv/static/sv/common.css
sv/static/sv/evenement_details.css
sv/templates/sv/_fichedetection_detail.html
sv/templates/sv/_latest_revision.html
sv/templates/sv/evenement_detail.html
sv/templates/sv/fichezonedelimitee_detail.html
sv/tests/test_evenement_details.py
sv/tests/test_evenement_performance_details.py
sv/tests/test_fichezonedelimitee_detail.py

Pour tous les objets d'un événement afficher la date et l'auteur de la dernière modification.
Les performances pourraient être améliorables en évitant de tout re-calculer dans la property `latest_version` de l'événement. Dans la mesure où on affiche toutes les versions des sous-objets sur la page on pourrait fournir la dernière version de chaque objet à la méthode pour éviter le recalcul.

Afficher les dates de dernières modifiations

---

core/mixins.py
core/views.py
sv/templates/sv/_evenement_action_navigation.html
sv/tests/test_evenement_ac_notification.py
sv/views.py

- Changement niveau UI pour cacher le bouton
- Vérification côté backend pour empécher l'action
@tglatt comme demandé dans le ticket mais je ne suis pas sur de comprendre nos règle actuelles. Pourquoi en brouillon le bouton est masqué et non pas grisé comme dans les autres cas ?

Ne pas permettre à l'AC de notifier à l'AC

---

sv/form_mixins.py
sv/tests/test_evenement_update.py

- Filtre les événements en brouillon des choix de liens libres dans le formulaire de modification d'un évènement
- Ajout d'un test pour vérifier qu'un événement en brouillon n'est pas sélectionnable dans la liste des liens libres
- Ajout d'un test pour vérifier que seuls les événements accessibles par l'utilisateur sont visibles dans la liste des liens libres selon leur visibilité

Exclusion des événements en brouillon des liens libres

---

sv/static/sv/evenement_details.js
sv/templates/sv/evenement_detail.html
sv/tests/test_evenement_details.py
sv/views.py

Points développés:
- Navigation automatique vers détection/zone après création/modification
- Sélection du bon onglet via URL params et classes CSS
- Optimisation des requêtes avec annotate/Min pour first_detection
- Gestion du cas sans détection(pour les tests)
- Correction d'une incompatibilité Chrome sur l'événement `dsfr.conceal`
La propriété `explicitOriginalTarget` de l'événement n'est pas supportée sur Chrome, contrairement à Firefox, ce qui causait une erreur `TypeError`. La correction utilise `event.target` qui est standardisé sur tous les navigateurs. Cela résout le bug de navigation dans les onglets qui empêchait la mise à jour correcte des actions de détection.

Affichage automatique de la détection ou zone après création/modification

---

sv/models/evenements.py
sv/tests/test_evenenement_visibilite_update.py

Empécher de changer la visibilité quand la l'événement est dans un état brouillon.

Empécher de changer la visibilité quand brouillon

---

core/forms.py
core/views.py
sv/tests/test_evenement_message.py
sv/tests/test_evenement_performance_details.py

Empêche les utilisateurs de forger l'URL / le formulaire pour envoyer un message sur un événement auquel ils n'auraient pas accès. Retrait du champ sender dans le form pour éviter d'augmenter les problème potentiel, l'expéditeur doit toujours être l'utilisateur à l'origine de la requête.

Empêcher les utilisateurs d'envoyer un message si pas accès

---

sv/factories.py

Corrige la factory qui faisait que les tests de mise à jour de prélévement ne fonctionnait pas toujours.
Avant le commit : sur 10 tentatives, 6 échecs
Après le commit : 10 OK sur 10 tentatives
Le cas ne se produisait que quand le prélévement était officiel.

Corriger la factory du prélévement

---

sv/form_mixins.py
sv/forms.py
sv/templates/sv/evenement_form.html
sv/templates/sv/fichedetection_form.html
sv/templates/sv/fichezonedelimitee_form.html
sv/tests/test_evenement_update.py
sv/tests/test_fichedetection_update.py
sv/tests/test_fichezonedelimitee_update.py
sv/tests/test_fichezonedelimitee_update_performance.py
sv/views.py

Dans le cas où quelqu'un a modifié un objet entre temps rendre impossible les modifications d'un objet pour éviter les conflits.

Ajouter un mécanisme pour empécher l'écrasement

---

core/views.py
sv/factories.py
sv/tests/test_evenement_contacts_remove.py
sv/tests/test_evenement_documents.py
sv/tests/test_evenement_performance_details.py
sv/tests/test_fichedetection_update.py
sv/tests/test_fichezonedelimitee_update.py
sv/tests/test_fichezonedelimitee_update_performance.py
sv/views.py

Repasse sur plusieurs vues afin de s'assurer que l'utilisateur à l'origine de la requête a bien le droit de réaliser une action liée a l'objet qu'il consulte / modifie.

Renforcer la sécurité de nombreuses vues

---

core/static/core/base.css
sv/templates/sv/evenement_form.html

- harmonise style des champs obligatoires
Problème : Les champs obligatoires n'avaient pas un style cohérent entre la création et la modification, car l'attribut HTML diffère (required vs data-required).
Solution : Ajout de sélecteurs CSS pour cibler les deux types d'attributs
- ajout organisme nuisible et statut réglementaire sur la fiche de modification d'un évènement

Champs obligatoires sur les formulaires de modification d'un lieu, prelevement et evenement

---

core/mixins.py
core/templates/core/_contact_add_form.html
core/templates/core/_structure_add_form.html
core/views.py
sv/tests/test_evenement_contact_add.py
sv/tests/test_evenement_structure_add.py

Corrige deux failles de sécurité où un attaquant pouvait forger une URL pour controler l'URL de redirection lors du clic sur le lien de retour vers l'événement.
Correction de plusieurs vues pour que la fonction de mise à jour du contexte soit bien prise en compte.

Corrige 2 failles open-redirect

---

requirements.txt

Mise à jour des dépendances indirectes pour passer sur des versions sans failles de sécurités connues (analyse Dependabot).

Mettre à jour les dépendances indirectes

---

sv/static/sv/fichedetection_prelevement_form.js

Problème:
Quand on fait une recherche dans Espèce de l’échantillon, on ne peut pas scroller donc on voit uniquement la première espèce.
Solution:
Modification du select pour que la liste s'ouvre vers le haut plutôt que vers le bas (ajout de l'option position "up" sur choicejs).

Amélioration de l'affichage du menu déroulant espece échantillon

---

sv/templates/sv/evenement_detail.html
sv/templates/sv/fichezonedelimitee_form.html
sv/tests/test_fichezonedelimitee_create.py
sv/tests/test_fichezonedelimitee_update.py
sv/tests/test_fichezonedelimitee_update_performance.py
sv/views.py

- Ajout de l'affichage des informations de l'événement sur le formulaire de création et MAJ
- Suppression des champs initialisés inutiles (dans la vue FicheZoneDelimiteeUpdateView/méthode get_initial)
- Ajout des tests correspondants
- Fix typo label statut réglementaire sur le détail de la fiche évènement

Ajout organisme_nuisible et statut sur formulaire de la fiche zone

---

sv/tests/test_fichedetection_update.py
sv/tests/test_utils.py

Le test pouvait fail car les champs concernant un lieu de type établissement étaient parfois masqués

Fix le test test_update_lieu

---

requirements.txt

Pour éviter les versions ayant des failles de sécurité connues.

Mettre à jour les dépendances secondaires

---

.env.dist
.github/workflows/django.yml
core/tests/test_settings.py
seves/settings.py
seves/urls.py

Cette PR améliore la sécurité de l'interface d'administration Django en 
- personnalisant son URL d'accès via une variable d'environnement. Cette modification empêche l'exposition de l'URL dans le code source et retire la valeur par défaut "admin",
- désactivant l'accès à l'administration par défaut.
- Ajout de la variable d'environnement DJANGO_ADMIN_URL
- Configuration du settings.py pour vérifier la présence de l'URL personnalisée
- Mise à jour des URLs pour utiliser la nouvelle configuration
- Validation de la présence de la variable au démarrage du serveur
- Ajout d'un test pour vérifier que l'ancienne URL "admin/" est non accessible
- Ajoute de la variable d'environnement DJANGO_ADMIN_ENABLED (activation explicite de l'interface - False par défaut)
- Retrait de django.contrib.admin …

Améliore la sécurité de l'interface d'administration Django

---

core/migrations/0024_document_is_infected.py
seves/settings.py
sv/tests/test_evenement_documents.py

Corriger deux migrations qui avaient le même numéro. N'oblige pas à la présence du settings `DJANGO_ADMIN_URL` si l'admin est désactivé.

Corriger les migrations et les settings

---

core/fields.py
core/mixins.py
core/static/core/structure_add_form.js
sv/forms.py
sv/templates/sv/evenement_detail.html
sv/tests/test_evenement_details.py
sv/tests/test_evenement_message.py
sv/tests/test_evenenement_visibilite_update.py

Cette PR est découpée en deux parties : 
- Amélioration de l'affichage de la visibilité 
Lorsque la visibilité est locale, on affiche la structure créatrice et les structures de l'AC (MUS et BSV).
J'ai ajouté une fonction `get_visibilite_display_text` dans le mixin `WithVisibiliteMixin` pour alléger la logique d'affichage dans le template.
Ajout des tests.
- Mise à jour visibilité : cases AC et créateur pré-cochées et désactivées 
Sur le formulaire d'ajout de structure lorsque la visibilité est limitée, les cases correspondantes à la structure créatrice et les structures de l'AC (MUS et BSV) sont cochées et désactivées.
Ajout d'un test.
J'ai volontairement laissé les deux commits pour bien séparer les modifs.

Amélioration affichage et mise à jour de la visibilité

---

sv/models/fiches_detection.py
sv/models/fiches_zone_delimitee.py
sv/tests/test_evenement_performance_details.py
sv/tests/test_fichedetection_update.py
sv/tests/test_models.py

En utilisant une cached_property pour les dernières version des détections et de la zone, on économise des requêtes SQL. En effet nous avons besoin de cette information à 2 endroits, une première fois pour la date de dernière modification d'une détection et une deuxième fois pour trouver la date de dernière modification d'un événément.

Améliorer les performances de l'événement

---

core/static/core/message.css
core/static/core/message_form.js
sv/templates/sv/evenement_detail.html
sv/tests/test_evenement_message.py

Afin que l'utilisateur ait une confirmation du type de message qu'il est en train de rédiger.

Ajouter le type de message dans la zone de rédaction

---

sv/managers.py
sv/tests/test_models.py

Qui empêchait de créer plus de 10 fiches au sein du même événement.

Corriger un bug dans la numérotation

---

pytest.ini

Comme la valeur n'est pas précisée dans pytest.ini, la valeur de l'env courant est prise, ce qui empêche d'activer l'admin en local.

Corriger la configuration des tests

---

sv/models/fiches_detection.py
sv/tests/test_evenement_performance_details.py

L'utilisation de values_list pouvait sembler une bonne idée, mais les lieux sont déjà pré-chargés par ailleurs. Construire la liste en python retire une requete SQL et sera aussi performant car le nombre de Lieux par fiche est faible (<100).
Comme on utilise plusieurs fois cette méthode sur la fiche événement (une fois par détection), plusieurs requêtes sont retirées dans un cas "réaliste".

Améliorer les performances de la page événement

---

sv/static/sv/evenement_details.css

Renvoit les fiches détection à la lignes quand il y a de nombreuses détections sur un événement (jusqu'à environ 50 dans les cas réels).

Améliorer l'affichage quand beaucoup de détections

---

.github/workflows/django.yml
pytest.ini

Les tests ne s’exécutaient pas à cause d'une erreur d'indentation du service Redis dans le fichier de configuration des GitHub Actions.

Corrige erreur indentation du service redis dans le fichier des GitHub Actions

---

sv/static/sv/evenement_details.js
sv/tests/test_evenement_details.py

- Simplifier le code
- Gérer un tag qui aurait déjà été sélectionné au chargement de la page
- Fixer le problème qui pouvait amener vers la mauvaise fiche en édition

Corriger les boutons d'actions pour les détections

---

core/views.py
sv/tests/test_evenement_message.py

Adapte la vérification des permissions pour aller chercher la fiche.

Permettre de supprimer un document lié à un message

---

sv/managers.py
sv/tests/test_fichedetection_soft_delete.py

Corriger la création du prochain numéro après la détection (logique) d'une fiche détection. L'utilisation du manager filtrait automatique sur les fiches non supprimées et causait une collission dans les numéros de fiches (alors qu'ils sont uniques). Utiliser le base_manager pour prendre en compte les fiches suprimées.

Corriger la création de numéro après suppression

---

core/static/core/base.js
core/templates/core/_contact_add_form.html
core/templates/core/_messages.html
core/templates/core/_show_form_errors.html
core/templates/core/_structure_add_form.html
core/templates/core/base.html
sv/static/sv/contact_add_form.js
sv/templates/sv/_fichezonedelimitee_form_zones_infestees.html
sv/templates/sv/fichedetection_form.html

Afin de préparer le travail pour les CSP, faciliter la maintenance et mieux séparer les intéractions du templating.

Retirer du JavaScript au sein du HTML

---

core/forms.py
core/mixins.py
sv/tests/test_evenement_details.py
sv/tests/test_evenement_message.py
sv/tests/test_evenement_visibilite_access.py
sv/tests/test_fiches_bloc_suivi.py

Modification de l'affichage de la visibilité : 
- Si l'évènement est LOCAL et que le créateur est AC, ne pas mettre deux fois la structure MUS ou BSV
- Si l'évènement est LIMITE, on voir MUS et BSV
Modification de la méthode `get_visibilite_display_text` et ajout du test `test_visibilite_display_text_when_evenement_locale_and_createur_ac`

Visibilité: modification affichage

---

sv/static/sv/fichedetection_form.js
sv/templates/sv/fichedetection_form.html

Supprime l'initialisation et la configuration de ChoiceJs pour le champ organisme nuisible sur le formulaire de modification d'un fiche détection (erreur js lors du chargement de la page).

Supprime la référence à l'organisme nuisible sur le form de modification d'une fiche détection

---

sv/static/sv/fichedetection_prelevement_form.js
sv/tests/test_fichedetection_create.py
sv/tests/test_utils.py

Problème :
Les attributs required ne sont pas retirés lors de la fermeture de la modale. 
Lors de l'ajout d'un nouveau prélèvement, les champs avec data-required ajoutent un attribut required. Mais quand j'annule le formulaire (via bouton annuler), le champ required reste. 
Donc lors de l'enregistrement de la nouvelle fiche, cela génère des erreurs js car les champs required sont vides et cachés.
Solution :
Retirer les attributs required ajoutés par data-required lors de la fermeture de la modale. 
De cette façon, lorsque la modale est fermée, tous les attributs required seront retirés, et le formulaire principal ne tentera pas de valider ces champs cachés.

Fix bug qui empêchait la création d'une nouvelle détection (sans évènement)

---

sv/templates/sv/_fichedetection_detail.html
sv/tests/test_fichedetection_detail.py

Corrige le problème d'ouverture du modale quand un événement contient plusieurs détections qui ont au moins un lieu. Comme le compteur utilisé est celui de la boucle on se retrouve avec plusieurs modales ayant le même ID. En utilisant le pk, nous avons la garanti que les modales auront bien des identifiants différents.

Corriger les modales sur l'événement

---

sv/factories.py
sv/filters.py
sv/tests/test_fiches_search.py

Permettre de rechercher par "sous-espèce" en cherchant toute les fiches dont l'ON commence par le terme recherché à la place d'une recherche exacte.

Élargir la recherche par organisme nuisible

---

core/forms.py
core/static/core/document.js
core/static/core/document_form.js
core/static/core/message_form.js
core/templates/core/_modale_ajout_document.html
core/validators.py
core/widgets.py
sv/templates/sv/_sidebar_message_form.html
sv/templates/sv/evenement_detail.html
sv/tests/test_evenement_documents.py
sv/tests/test_evenement_message.py
sv/views.py

- Ajoute une limite de taille lors de l'upoad d'un fichier via le formulaire d'ajout de document et via l'ajout d'un élément de suivi (message, note...),
- Vérification effectuée côté backend et frontend,
- Affiche un message d'erreur dès la sélection du fichier si celui-ci dépasse la limite autorisée,
- Ajout d'une indication sur la taille limite à respecter
- la constante `MAX_UPLOAD_SIZE_BYTES` est dans le fichier `validator.py` pour garder une cohérence avec le reste (extensions autorisées)

Ajout limite de taille pour l'upload d'un document

---

core/static/core/message_form.js
sv/templates/sv/_document_warning_modal.html
sv/templates/sv/_sidebar_message_form.html
sv/templates/sv/evenement_detail.html
sv/tests/test_evenement_message.py

Ajoute un message de confirmation quand l'utilisateur va envoyer son message avec un document non validé (formulaire rempli mais non confirmé). L'utilisateur a deux choix: envoyer en validant ou non le denier document.
- Refactoring du JS pour éclaircir un peu le code
- Ajout de tests sur les 2 nouveaux cas

Ajouter un message de confirmation pour les documents

---

seves/settings.py

Forcer le téléchargement des documents au clic sur le lien de téléchargement plutôt que la consultation dans le navigateur pour le format supportés (images, PDF, etc.)
https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/put_object.html#
https://www.rfc-editor.org/rfc/rfc6266#section-4

Forcer le téléchargement des documents

---

sv/managers.py
sv/tests/test_fichedetection_export.py
sv/tests/test_fiches_search.py
sv/tests/test_fichezonedelimitee_create.py
sv/tests/test_fichezonedelimitee_update_performance.py

En triant sur la chaine de caractères on se retrouve dans une situation où la détection 2025.1.1 est affichée avant (plus haut) que la détection 2025.1.10 qui est pourant "plus récente".
Ce commit adapte le tri pour que ce problème ne survienne plus. L'utilisation d'un objet extérieur (événement) dans le tri sera probablement plus lent.
- Ajout d'un test sur le tri des zones pour vérifier que cela était bien ok
- Correction d'un test qui utilisait des numéros non valides

Corriger l'ordre des détections dans vue de liste

---

core/mixins.py
sv/models/evenements.py
sv/tests/test_evenement_etats.py

Problème: lorsque l'évènement est clôturé, on ne le voit pas sur la fiche de l'évènement. Le tag affiché est Fin de suivi.

Affiche le tag clôturé si l'évènement est clôturé

---

core/static/core/contact_add_form.css
core/templates/core/base.html
sv/static/sv/contact_add_form.js
sv/static/sv/evenement_form.js
sv/static/sv/fichedetection_form.js
sv/static/sv/fichedetection_lieux_form.js
sv/tests/test_evenement_update.py

Mise à jour de la bibliothéque choicesjs pour avoir les dernières méthodes a disposition (nécessaire pour un ticket a venir).
- Les listes de classes ne sont plus autorisées
- Quelques changement dans la structure des événements

Mettre à jour choicesjs

---

sv/filters.py
sv/tests/test_fiches_search.py

Corrige le cas où l'on veut rechercher uniquement avec une année.

Corriger la recherche pour la zone

---

sv/factories.py
sv/tests/test_fichedetection_detail.py
sv/tests/test_fichedetection_update.py

Améliore la factory du Lieu qui ne pouvait pas être utilisé avec .build() à cause de la manière dont était utilisé le département. Refactoring des tests en mimiquant la méthode baker, c'est à dire sans créer l'objet en lui même mais en créant les objets reliés. Changement du type de la factory pour les coordonnées afin de coller avec ce qui est en base de donnée.

Améliorer les factories et les utiliser

---

core/static/core/message_form.js

Dans le scénario suivant:
- Je fais un nouvel élément de suivi de type compte rendu sur DI
- Je ferme la sidebar
- Je fais un nouvel élément de suivi d'un autre type (message par exemple)
Les cases a cocher (choix de destinataire limité) ne devraient pas être affichées car elle ne servent que pour le compte rendu sur DI.

Corriger l'affichage des destinataires

---

core/static/core/document_form.js
sv/static/sv/view_manager.js

Dans le cas d'une fiche en brouillon certains éléments HTML ne sont pas existant. N'initialiser les composants uniquement quand cela est possible.

Vérifier que des éléments existent avant utilisation

---

core/mixins.py
sv/models/evenements.py
sv/templates/sv/_cloturer_modal.html
sv/templates/sv/_evenement_action_navigation.html
sv/tests/test_evenement_etats.py
sv/view_mixins.py
sv/views.py

Cette PR permet a un agent de l'AC de clôturer un évènement même si sa structure est la dernière à ne pas avoir mis fin au suivi.
- centralisation de la logique de clôture dans la méthode `can_be_cloturer`,
- la méthode `can_be_cloturer_by` à été modifiée pour seulement vérifier si un user a le droit de clôturer un évènement,
- renommage des variables dans les templates pour une meilleurs compréhension : 
- `is_evenement_can_be_cloturer_by_user` : est-ce que le user a le droit de clôturer l'évènement
- `is_evenement_can_be_cloturer` : est-ce que l'évènement peut être clôturer
- création d'un mixin `WithClotureContextMixin` pour regrouper les différentes variables nécessaires dans les templates pour la clôture,
- modification de la view `EvenementCloturerView` pour …

Permettre à l'AC de clôturer quand il est le dernier sans fin de suivi

---

core/static/core/message_form.js

Les blocs de destinataire et copies aux structures n'étaient pas cachés quand on changeait de type de message.

Corriger l'UI de rédaction des messages

---

sv/templates/sv/_evenement_action_navigation.html
sv/tests/test_evenement_etats.py
sv/view_mixins.py

Cette PR permet de masquer le bouton clôturer lorsque l'évènement l'est déjà.
Suppression de la partie Fin de suivi dans le test `test_can_cloturer_evenement_if_creator_structure_in_fin_suivi` car non nécessaire.

Masque le bouton clôturer lorsque l'évènement l'est déjà

---

core/static/core/message_form.js

Pour l'envoi de message, ne se produit que sous Chrome.

Empécher de soumettre plusieurs fois le formulaire

---

sv/tests/test_models.py

Le test pouvait générer une structure préleveuse "Exploitant" sachant que le prélèvement est officiel (impossible d'après règle métier - cf. méthode clean du model Prelevement)

Corrige un test qui pouvait générer une incohérence

---

core/forms.py
sv/tests/test_evenement_message.py

Depuis le changement de destinataires sur les DI les destinataires n'étaient plus enregistrés en base.
De plus j'ai changé la logique de la liste déroulante qui proposait uniquement les structures de la fiche pour proposer toutes les structures qui sont joignable (cohérent avec le type message).
Ajout d'un test pour vérifier que tout est ok et que les destinataires sont bons.

Corriger les demandes d'intervention

---

conftest.py
sv/static/sv/fichezone_form.js
sv/tests/test_fichezonedelimitee_create.py
sv/tests/test_fichezonedelimitee_update.py

Dans l'interface d'édition de la zone bloquer dans l'interface les détections qui auraient déjà été sélectionnées dans un autre picker. Ainsi un utilisateur ne peut plus avoir l'erreur back disant qu'une détection donnée a été sélectionnée à la fois dans une ZI et en hors zone infestée, ou alors dans deux ZI différentes.
J'ai essayé plusieurs approches, les contraintes a prendre en compte étant:
- Que la recherche fonctionne toujours
- Gérer l'ajout et la supression de détection dans un picker
- Le nombre de picker est variable dans le temps (il est possible d'ajouter ou de supprimer des ZI)
Une autre approche était d'ajouter l'attribut disabled directement au niveau de l'élément HTML, mais cela me forçait a demander a choiceJS le rafraichissement des dropdowns. En utilisant setChoices, …

Bloquer la sélection de détections déjà sélectionnées

---

sv/tests/test_fichedetection_update.py
sv/view_mixins.py
sv/views.py

Vérifier que la sauvegarde fonctionne bien pour les anciennes fiches contenant des valeurs inactives (labo, structures préleveuses). Le test ne faisait que vérifier que la page chargait bien et que l'option était dans la liste déroulante, mais lors de la sauvegarde l'utilisateur avait un message d'erreur car l'option choisie n'était pas dans la liste des options possibles.
Amélioration du message d'erreur pour affiche le nom du champ en erreur le cas échéant.

Autoriser l'enregistrement pour les anciennes valeurs

---

sv/static/sv/evenement_details.js
sv/static/sv/fichedetection_form.js
sv/templates/sv/evenement_detail.html
sv/templates/sv/fichedetection_form.html
sv/tests/test_fichedetection_form.py
sv/tests/test_utils.py

Lorsque j'ajoute une nouvelle détection (ou modifie) depuis la page de détail d'un évènement, je peux annuler et revenir à la page de détail de l’évènement dans le même état (avec la même détection sélectionnée).
- Ajout de la fonction `updateAddDetectionLink` pour gérer la mise à jour de l'URL du bouton d'ajout d'une nouvelle détection lorsqu'on change la détection à visualiser et ajout de la variable `back_link` dans le context de la view `FicheDetectionCreateView`,
- Pour la modification, ajout de la variable `back_link` dans le context de la view `FicheDetectionUpdateView`,
- Modification de quelques tests pour différencier le lien ajouté de ceux existant dans les modales pour les formulaires d'ajout/modification d'un lieu et prélèvement.

Ajouter un bouton annuler dans le formulaire d’une fiche détection

---

sv/factories.py
sv/tests/test_evenement_details.py
sv/tests/test_evenement_performance_details.py
sv/tests/test_fichedetection_detail.py
sv/views.py

- Sélectionner la première fiche de détection par numéro et non par ID dans la vue détail événement
- MAJ des tests avec factories
* Remplacement de baker par des factories dans quelques tests
* Ajout d'une méthode create_miniaml pour créer une factory Lieu ou Prelevement avec uniquement les champs obligatoires
* Ajout de la factory PosistionChaineDistribution

Trier les fiches de détection par numéro séquentiel et non par ID

---

core/forms.py
core/static/core/message.css

- Corrige l'espacement du raccourci dans le cas des demandes d'intervention
- Replace l'astérisque au bon endroit en contournant la règle CSS et en l'ajoutant de la label
- Retirer les précisions sur les suffix label car déjà défini dans le DSFRForm

Améliorer l'affichage des labels pour les messages

---

cron.json

Si Redis venais a avoir un problème, les documents serait tout de même scanés et les mails envoyés.

Ajouter un cron en cas de problème avec le broker

---

core/forms.py
core/notifications.py
sv/tests/test_evenement_message.py
sv/tests/test_notifications.py

Pour les points de situation les destinataires étaient ajouté à la voléee au moment de l'envoi du message. Cela empêche de savoir dans l'interface qui a reçu le message.
En déplaçant la logique de l'envoi de la notification au nettoyage des données dans le formulaire, les données sont correctement enregistrées en base et on retombe alors dans le cas "classique" (affichage dans le tableau et dans le détail du message).
Ajout d'un test spécifique au point de situation.

Stocker et afficher les destinataires points de situation

---

conftest.py
core/static/core/message.css
core/static/core/message_form.js
sv/tests/test_evenement_message.py

Ce commit corrige une combinaison de deux problèmes qui fait qu'un message pouvait être validé sans aucun champs de remplis (causant une ou des erreurs côté backend).
- Au niveau de JS le form n'était pas validé avant l'envoi
- Au niveau de ChoicesJS, le champ initial est bien required mais masqué complétement par la bibliothèque (display: none !important) ce qu'il fait qu'il ne rentre pas en compte dans la validation du formulaire.
Pour corriger le deuxième problème j'ai opté pour une méthode de masquage différente qui garde le champ actif mais le cache de l'affichage, il est ainsi consévé dans la validation. Ce changement de comportement oblige a beaucoup de changement dans les tests pour être sur de sélectionner la bonne option.
https://github.com/Choices-js/Choices/issues/1061

Rendre obligatoire les champs required du message

---

core/mixins.py
core/signals.py
core/views.py
seves/settings.py

Dans le cas où Redis ne serait pas joignable on améliore la gestion des erreurs.
Au lieu d'afficher une erreur 500, on affiche un message d'erreur et on loggue l'erreur dans Sentry pour être capable de détecter le problème.

Améliorer la gestion des erreurs pour Redis

---

sv/static/sv/fichedetection_lieux_form.js
sv/tests/test_fichedetection_update.py

Lorsqu'on efface la commune via ChoiceJS les champs masqués associés à la commune n'étaient pas effacés.

Corriger un bug de remplissage des communes

---

core/auth_views.py
core/templates/login_denied.html
seves/settings.py

En cas de compte existant mais inactif (is_active = False dans le modèle User de Django) personaliser le message d'erreur pour afficher les noms des gens qui peuvent débloquer la situation.
Changement d'un paramètre pour éviter des users aux utilisateurs non-existants dans notre import.

Ajouter une page d'erreur explicite si compte inactif

---

core/management/commands/import_contacts.py
core/tests/test_import_contacts.py

Cette PR permet d'importer les contacts liés à une structure DDETSPP.
Modification des tests pour prendre en compte cet ajout.
Je ferai une autre PR pour améliorer/factoriser quelques tests.

Ajout des contacts DDETSPP dans l’import AGRICOLL

---

sv/static/sv/evenement_details.js
sv/views.py

Cette PR permet d'arriver en haut de la page quand on revient sur l’évènement après création ou modification d'une fiche zone délimitée.
Initialement, le lien de redirection incluait un hash (#tabpanel-zone-panel) vers l'onglet zone et au chargement de la page la navigateur se positionné dessus. Par conséquent, le haut de la page de l'évènement n'était plus visible.
- suppression du hash pour supprimer l'effet de positionnement natif du navigateur sur l'onglet Zone,
- ajout du paramètre `tab` dans l'URL suite à une création ou modification d'une fiche zone délimitée,
- au chargement de la page, si le paramètre tab est a `zone`, alors sélection automatique de l'onglet (via API js DSFR)
- ~~ajout d'un écouteur dsfr.ready ou dsfr.start pour éviter que la fonction ne …

Arriver en haut de la page quand on revient sur l’évènement après création/modif fiche zone

---

conftest.py
sv/tests/test_evenement_message.py

- Change la méthode pour sortir du picker quand on a fini de sélectionner les agents (clic ailleurs à la place de la touche Echap)
- Rend plus précis l'endroit où le clic est fait

Améliorer la fiabilité d'un test

---

sv/static/sv/fichedetection_lieux_form.js

- Déclencher la création du composant ChoicesJS au dernier moment permet de corriger le problème qui arrivait dans un scénario ouverture du modale, fermeture sans compléter, ouverture de la même modale. Le composant n'était alors plus intéractif (probablement car on manipule le DOM en même temps).
Cette solution permet aussi d'éxecuter du JS supplémentaire uniquement quand on en a besoin.

Corriger un bug sur les picker de commune

---

core/managers.py
core/mixins.py
core/tests/test_managers.py
sv/tests/test_evenement_contacts_list.py

Cette PR permet de modifier le tri dans la liste des contacts (sur le détail d'un évènement) :
- pour les structures → triée par libellé
- pour les agents → triée par : 
1. libellé des structures
2. nom de l’agent
3. prénom de l’agent

Modification du tri dans la liste des contacts

---

core/static/core/message_form.js
sv/templates/sv/_sidebar_message_form.html
sv/tests/test_evenement_message.py

Permet de rendre obligatoire la sélection d'au moins une case à cocher dans les destinataire pour un élément de suivi de type "CR sur DI".

Destinataires en obligatoire pour CR sur DI

---

sv/models/lieux.py
sv/tests/test_fichedetection_create.py

Dans la mesure où le site d'inspection était dans la liste `ETABLISSEMENT_FIELDS` le champ était vidé si la case d'établissement n'était pas cochée.

Corriger la sauvegarde du site d'inspection sur le lieu

---

.env.dist
core/static/core/base.css
core/templates/core/base.html
seves/context_processors.py
seves/settings.py

Cette PR permet d'ajouter un bandeau "Recette" fixe sur l'environnement de recette.
Dans les settings, j'ai ajouté la variable d'environnement `ENVIRONMENT` pour distinguer les différents environnements (dev, recette, prod).
Pour l'instant elle est utilisée uniquement pour la recette (cf. fonction `environment_class()` dans `seves/context_processors.py`.
Sur Scalingo, la variable `ENVIRONMENT` a été ajouté dans l'app de la recette.

Ajout d'un bandeau sur la recette et en local

---

seves/settings.py

Puisque SENTRY_ENVIRONMENT a été supprimé dans un précédent commit, des erreurs de recette remontaient dans la production sur Sentry.

Ajout du paramètre environment dans l'initialisation de Sentry

---

sv/templates/sv/fichedetection_detail_lieu.html

Dans la modale de détails du lieu changer l'ordre des informations pour correspondre à l'ordre du formulaire.

Changer l'ordre d'affichage des champs du lieu

---

core/migrations/0009_agent_structure_alter_contact_options_and_more.py
core/migrations/0015_lienlibre_lienlibre_no_self_relation.py
core/migrations/0021_remove_contact_contact_has_structure_or_agent_and_more.py
core/models.py
sv/migrations/0027_remove_zoneinfestee_numero_and_more.py
sv/migrations/0030_alter_fichedetection_numero_and_more.py
sv/migrations/0041_alter_fichezonedelimitee_numero_and_more.py
sv/migrations/0054_prelevement_check_officiel_fields_empty_or_null.py
sv/models/fiches_detection.py
sv/models/prelevements.py

Afin de rester compatibles avec les prochaines versions de Django, check étant devenu déprécié. Permet de retirer quelques warnings dans les tests.

Migrer les check en condition dans les modèles

---

sv/tests/test_evenement_contact_add.py

A cause d'une imprécision dans la zone où il faut cliquer.

Corriger un test qui rate aléatoirement

---

sv/filters.py
sv/tests/test_evenement_search.py

Problème :
La recherche avec un tiret dans le numéro de l'évènement génère une erreur (exemple: 2025-15)
Solution :
Modification du contrôle côté front et back pour supprimer la possibilité de recherche avec un tiret dans le numéro.

Corrige un bug dans la recherche d'évènement

---

sv/managers.py
sv/tests/test_evenement_search.py

Problème :
Si un évènement comporte trois fiches détections et que j'en supprime une, le nombre de détections affichées dans la liste des évènements (colonne Détections) est à trois au lieu de deux.
Solution :
Dans la colonne Détections dans la page liste des évènements, filtrer pour ne plus prendre en compte les fiches détections supprimées

Corrige un bug dans la colonne Détections dans la liste des évènements

---

core/views.py
sv/tests/test_evenement_ac_notification.py
sv/tests/test_evenement_delete.py
sv/tests/test_evenement_etats.py
sv/tests/test_evenement_update.py
sv/tests/test_evenenement_visibilite_update.py
sv/tests/test_fichedetection_create.py
sv/tests/test_fichezonedelimitee_add_performance.py
sv/tests/test_fichezonedelimitee_create.py
sv/tests/test_fichezonedelimitee_update.py
sv/views.py

Cette PR corrige des accès non autorisés. Liste des actions traitées et/ou améliorées : 
<ins>Publier l’évènement</ins>
- ajout du test `test_cant_publish_evenement_i_cant_see`
<ins>Déclarer à l’AC</ins>
- ajout de `UserPassesTestMixin` dans la view `ACNotificationView`
- ajout du test test `test_cant_forge_notify_ac_of_evenement_i_cant_see`
<ins>Modifier la visibilité</ins>
- 2 tests ajoutés : 
- `test_users_not_from_ac_cant_forge_update_visibilite` et 
- `test_cant_forge_update_visibilite_of_evenement_i_cant_see`
<ins>Modifier l’évènement</ins>
- ajout du test `test_cant_update_evenement_i_cant_see`
<ins>Supprimer l’évènement</ins>
- ajout du test `test_cant_delete_evenement_i_cant_see`
<ins>Ajouter une détection</ins>
- ajout du mixin `UserPassesTestMixin` dans la view …

Fix failles de sécurité concernant l'accès à des actions non autorisées

---

sv/static/sv/fichedetection_form.css
sv/templates/sv/fichedetection_form.html
sv/views.py

Cette PR permet d'ajouter l'organisme nuisible et le statut réglementaire dans le formulaire de la fiche détection lorsque l'évènement existe.
J'ai ajouté une condition d'affichage pour les champs `organisme_nuisible` et `statut_reglementaire` du formulaire pour éviter d'avoir l'espace entre le titre et le premier champ du bloc "Objet de l'évènement".

Ajout ON et statut régl. lecture seule dans form détection

---

sv/static/sv/evenement_details.css
sv/static/sv/evenement_details.js
sv/templates/sv/_fichezonedelimitee_cartographies.html
sv/tests/test_evenement_details.py

- Dans le bloc Cartographie de l'onglet zone, ajout d'une notice d'information avec lien vers l'onglet Documents.
- Ajout du hash d'ID dans l'URL lors du clic sur les onglets
Le système d'onglets ne détectait pas correctement les changements d'URL, ce qui empêchait la navigation entre onglets après avoir cliqué sur le lien documents de la notice (l'event listener sur le hash ne détecte pas de changement d'url).

Ajout notice et lien vers l'onglet Documents depuis le bloc Cartographies

---

core/mixins.py
core/templates/core/_carte_resume_contact_agent.html
core/templates/core/_carte_resume_contact_structure.html
core/templates/core/_carte_resume_document.html
core/templates/core/_contacts.html
core/templates/core/_documents.html
core/views.py
sv/models/evenements.py
sv/models/fiches_detection.py
sv/models/fiches_zone_delimitee.py
sv/templates/sv/_evenement_action_navigation.html
sv/templates/sv/evenement_detail.html
sv/templates/sv/fichezonedelimitee_detail.html
sv/tests/test_evenement_ac_notification.py
sv/tests/test_evenement_contact_add.py
sv/tests/test_evenement_contacts_remove.py
sv/tests/test_evenement_details.py
sv/tests/test_evenement_documents.py
sv/tests/test_evenement_etats.py
sv/tests/test_evenement_performance_details.py
sv/tests/test_evenement_update.py
sv/tests/test_evenenement_visibilite_update.py
sv/tests/test_fichedetection_create.py
sv/tests/test_fichedetection_soft_delete.py
sv/tests/test_fichedetection_update.py
sv/tests/test_fichezonedelimitee_create.py
sv/tests/test_fichezonedelimitee_delete.py
sv/tests/test_fichezonedelimitee_update.py
sv/view_mixins.py
sv/views.py

Cette PR permet de restreindre l'accès à certaines actions lorsqu'un évènement est clôturé. Les seules actions qui restent accessibles sont celles liées au fil de suivi.
- dans les modèles `Evenement`, `FicheDetection`, `FicheZoneDelimitee`, ajout de méthodes pour regrouper la logique d'accès à certaines actions,
- dans la view `EvenementDetailView`, ajout de la méthode `get_permission_context`. Permet d'ajouter dans le context les différentes actions possibles d'effectuer,
- modification des templates pour masquer les actions si nécessaire,
- modification de la méthode `test_func` pour différentes view pour invoquer les méthodes ajoutées dans les modèles `Evenement`, `FicheDetection`, `FicheZoneDelimitee`,
- `is_cloture` en property,
- suppression de la méthode …

Désactive les actions quand l’évènement est clôturé

---

.talismanrc
seves/settings.py
ssa/static/ssa/_rappel_conso_link.js
ssa/templates/ssa/evenement_produit_detail.html
ssa/tests/test_evenement_produit_details.py

Pour les numéros de rappel conso ajouter dynamiquement un lien vers la bonne fiche si elle est trouvée dans l'API.
Appel réalisé côté frontend pour plusieurs raisons:
- Pas besoin d'authentification
- Possilibité d'avoir plusieurs numéros sur une fiche alors que l'API ne semble gérer qu'un numéro par appel. Il faut donc faire plusieurs appels API ce qui pourrait considérablement ralenti le backend.
- Fonctionnalité qui n'est pas nécessaire au bon fonctionnement de l'application, en cas de problème au niveau de l'API il n'y aura pas d'impact sur le backend.

Ajouter un lien dynamique vers rappel conso

---

sv/tests/test_evenement_contact_add.py
sv/tests/test_evenement_structure_add.py

- Dans `test_add_structure_form_hides_structure_without_active_user` il est possible que 2 structures aient un nom similaire (par exemple Thing et Something) ce qui fausse le test.
- Pour `test_add_multiple_contacts_agents_to_an_evenement` rend le sélecteur plus précis.

Fiabiliser des tests

---

account/forms.py
core/filters.py
core/form_mixins.py
core/forms.py
core/static/core/free_links.js
core/templates/core/_list_free_links.html
ssa/form_mixins.py
ssa/forms.py
ssa/managers.py
ssa/models/evenement_produit.py
ssa/static/ssa/evenement_produit_form.css
ssa/static/ssa/evenement_produit_form.js
ssa/templates/ssa/evenement_produit_detail.html
ssa/templates/ssa/evenement_produit_form.html
ssa/tests/pages.py
ssa/tests/test_evenement_produit_creation.py
ssa/tests/test_evenement_produit_details_performances.py
ssa/views/produit.py
sv/filters.py
sv/form_mixins.py
sv/forms.py
sv/static/sv/evenement_form.js
sv/templates/sv/evenement_detail.html
sv/templates/sv/evenement_form.html

Dans SSA permettre l'ajout de lien libres à la création de la fiche, les liens peuvent alors être vus depuis la page détails de la fiche.
- Factoriser les forms mixins de core dans un fichier à part
- Factoriser de la logique depuis SV dans core pour pouvoir l'utiliser dans SSA
- Changer le form et la vue pour gérer les liens libres

Permettre l'ajout de lien libre sur les fiches produit

---

.talismanrc
ssa/models/evenement_produit.py
ssa/tests/pages.py
ssa/tests/test_evenement_produit_details.py
ssa/views/produit.py

Vérifier que l'utilisateur a bien le droit d'accèder à la fiche.

Filtrer l'accès à la page ÉvénementProduit sur SSA

---

sv/templates/sv/fichedetection_form.html
sv/tests/test_fichedetection_create.py

Cette PR corrige l'affichage de la date de création dans le formulaire d'une fiche détection.
La date affichait la date du jour même lors de la modification de la fiche.

Corrige affichage de la date création dans formulaire de fiche détection

---

sv/forms.py

Scénario à suivre pour reproduire le bug (effectué le 15/04/2025) : 
- Une fiche dont la date de création est le 14/04/2025,
- Je la modifie,
- Date de 1er signalement : je ne peux rentrer qu’une valeur antérieure à 11/04/2025.
La date max du 1er signalement est censé être égale à la date du jour (15/04/2025). Au moment ou j'ai reproduit le bug, je vois que le dernier déploiement date du 11/04/2025.
Déplace l'évaluation de `datetime.date.today()` dans la méthode `__init__` du formulaire pour éviter que la date maximum ne soit figée au démarrage du serveur. 
Assure ainsi que la contrainte de date maximale reflète toujours la date courante, quel que soit le moment du dernier déploiement.

Corrige la date max du 1er signalement dans formulaire fiche détection

---

.talismanrc
core/static/core/ban_autocomplete.js
seves/settings.py
ssa/forms.py
ssa/static/ssa/_etablissement_form.js
ssa/templates/ssa/evenement_produit_form.html
ssa/tests/pages.py
ssa/tests/test_evenement_produit_creation.py

En utilisant l'API de la BAN on permet l'autocomplétion sur le champ adresse (ajout de la ville, département, etc.).
Permet aussi de forcer la valeur si jamais l'information n'est pas présente dans la BAN et/ou pour des adresses à l'étranger.

Ajouter l'autocomplete sur les adresses

---

ssa/tests/test_evenement_produit_details.py

Utiliser exact=True pour éviter les doublons potentiels (par exemple "Non" dans le bloc information pour le cerfa reçu et la valeur "Non alerte")

Fiabiliser les tests de détails événement produit

---

core/mixins.py
sv/templates/sv/_cloturer_modal.html
sv/templates/sv/_evenement_action_navigation.html
sv/tests/test_evenement_etats.py
sv/view_mixins.py
sv/views.py

Problème :
Aujourd’hui, si l’AC veut clôturer une fiche, il faut que toutes les structures de la fiche aient mis “fin de suivi”.
Ce qui a été fait :
- Suppression de la règle de dépendance de la clôture à la fin de suivi par toutes les structures de la fiche,
- L’AC peut clôturer même si aucune structure n’a mis fin au suivi,
- Modification du message d’avertissement à la clôture,
- Conservation de l'ajout automatique de la structure (MUS ou BSV) en fin de suivi si c'est la seule qui ne l'est pas.

Modification du process de clôture d'un évènement

---

.talismanrc
requirements.in
requirements.txt
seves/settings.py
seves/wsgi.py

- La dépendance dj-static fait fail la CI.
- Ajout de la dépendance WhiteNoise pour servir les fichiers static en production.
J'ai ajouté le fichier `.talismanrc` pour l'erreur générée lors de l'execution du hook de precommit suivante : 
`seves/settings.py" failed checks against the pattern ^settings.py$`

Remplacement de dj-static par WhiteNoise

---

sv/static/sv/fichedetection_form.css
sv/static/sv/fichedetection_form.js
sv/templates/sv/fichedetection_form.html
sv/tests/conftest.py
sv/tests/test_fichedetection_create.py

Cette PR corrige un problème d'alignement des champs organisme nuisible et statut réglementaire dans le formulaire de la fiche détection (si évènement existant).

Corrige problème alignement (ON et statut) dans form fiche detection

---

ssa/forms.py
ssa/tests/test_evenement_produit_creation.py

Autoriser les chaînes à 6 chiffres comme sur le modèle.

Corriger la validation d'input du numéro RASFF

---

sv/templates/sv/evenement_detail.html

Modification du wording du toggle sur SV par “Affichage détaillé/Synthèse” au lieu de “Détail/Synthèse”

Modification du wording du toggle “détail/synthèse”

---

core/templates/core/_documents.html

Corrige un problème d'affichage dans l'onglet document (champs type de document et structure) lorsque le formulaire d'ajout de message est affiché.
Avant :
Après :

Corrige problème affichage onglet documents

---

sv/templates/sv/_cloturer_modal.html
sv/tests/test_evenement_etats.py
sv/tests/test_evenement_performance_details.py
sv/view_mixins.py

- modification du titre (ajout du numéro de l'évènement),
- modification du wording si la structure MUS (ou BSV) est la seule qui n’est pas en fin de suivi.

Modification titre et wording modale clôture évènement

---

core/forms.py
core/models.py
core/static/core/document.js
core/static/core/document_form.css
core/static/core/document_form.js
core/static/core/message_form.js
core/templates/core/_modale_ajout_document.html
core/templates/core/base.html
core/validators.py
core/widgets.py
sv/templates/sv/_sidebar_message_form.html
sv/tests/test_evenement_documents.py
sv/tests/test_evenement_message.py
sv/views.py

Cette PR permet d'introduire la possibilité de restreindre des extensions de fichier par type de document (dans les formulaires d'ajout de document dans l'onglet Documents et l'ajout d'un élément de suivi).
Pour l'instant, seul le type de document "Cartographie" est géré.
Côté backend :
- Dans le modele `Document`, ajout d'un dictionnaire (`ALLOWED_EXTENSIONS_PER_DOCUMENT_TYPE`) permettant de stocker les extensions autorisés par type de document,
- Conversion de la liste des extensions autorisés en `TextChoices` pour éviter la répétition des extensions sous forme de chaîne de caractères et d'éventuelles erreurs de recopie,
- Idem pour la liste des MimeType autorisés (pour garder une cohérence),
- Dans le modèle `Document`, ajout d'une méthode `validate_file_extention_for_document_type` …

Contraindre les extensions selon le type de document (Cartographie)

---

core/static/core/message_form.js
sv/tests/test_evenement_message.py

Problème:
Si je quitte la modale de confirmation d'envoi de message (car ajout de document non validé), le bouton d'envoi de message est disabled.
Ce qui a été fait:
- Ajout d'un listener sur la fermeture de la modale sans envoi du message pour réactiver le bouton d'envoi du message,
- Ajout d'un test.

Corrige le bug d'envoi de message si on quitte la modale confirmation

---

ssa/static/ssa/evenement_produit_list.js
ssa/templates/ssa/evenementproduit_list.html
ssa/tests/pages.py
ssa/tests/test_evenement_produit_list.py

Faire fonctionner le bouton de reset aussi quand les champs sont déjà remplis au chargement de la page (par exemple quand une recherche a déjà été faite). On copie le comportement que l'on a sur SV.

Améliorer le reset du formulaire de recherche sur SSA

---

core/filters_mixins.py
sv/filters.py
sv/static/sv/evenement_list.js
sv/templates/sv/evenement_list.html
sv/tests/test_evenement_search.py
sv/tests/test_fiche_list_performances.py

Ajout de deux filtres supplémentaire dans le formulaire de recherche d'évènements :
- Structure en contact : récupère les évènements dont dans la structure sélectionnée est dans la liste des contacts
- Agent en contact : récupère les évènements dont dans l'agent sélectionné est dans la liste des contacts

Ajout filtres pour structures et agents en contact

---

ssa/static/ssa/evenement_produit_form.css
ssa/tests/pages.py

Sur les tag de rappel conso, ne faire disparaitre le numéro uniquement au clic sur la croix et pas sur l'ensemble du tag.

Permettre le clic uniquement sur la croix de rappel conso

---

sv/tests/test_evenement_contact_add.py

Dans certains cas le picker de contact se retrouve tout en bas de la page (en fonction du contenu de l'événement, du nombre de fiche, etc.). Au clic le menu déroulant s'ouvre vers le haut et certains éléments passent sous les blocs qui sont au dessus. Cela rend impossible la sélection du contact désiré.
Ce problème n'arrive pas pour les utilisateurs car le clic sur l'onglet fait scroller le navigateur (ce qui ne semble pas être le cas d'après la trace Playwright du test en échec).
Pour reproduire en tant qu'utilisateur il faut cliquer sur l'onglet et après jouer avec le scroll pour positionner le champs en bas de l'écran, puis cliquer dans le champ contact et saisir sa requête.
J'ai essayé rapidement de comprendre le problème de masquage des blocs sans en comprendre vraiment la source. …

Améliorer la fiabilité des tests de contacts

---

ssa/tests/pages.py
ssa/tests/test_evenement_produit_creation.py

- Corrections des tests existants qui n'utilisaient pas le mock défini et ajout d'une assertion pour plus que cela n'arrive
- Utilisation d'un mock pour tous les autres tests où une adresse fictive est forcée de manière a faire moins d'appels réseau et fiabiliser les tests

Améliorer les tests des établissements SSA

---

.talismanrc
seves/middlewares.py
seves/settings.py
sv/tests/test_access.py

- Si un utilisateur peut voir les deux domaines, le rediriger en priorité vers SSA (plus d'activité que sur SV).
- Si un utilisateur consulte un domaine, le ramener post login sur ce prochain domaine par défaut (ne concerne que les utilisateurs qui peuvent voir plusieurs domaines).

Améliorer le comportement post-login des domaines

---

.talismanrc
seves/auth.py
seves/context_processors.py
seves/middlewares.py
seves/settings.py

Lors du processus d'authentification / identification récupérer l'agent et la structure de l'agent ainsi que les groupes de l'utilisateur. Cela permet de gagner plusieurs requêtes sur chaque page (agent et structure sont utilisés partout dans le code, les groupes sont utilisés aussi à plusieurs endroits).
Cela ne se reflète pas dans les tests car la partie auth est complétement mocké.
En local sur la vue de liste de SV je passe de 16 requetes à 12 requetes.
⚠️  Les utilisateurs seront déconnecté lors du déploiement de se commit a cause du changement de "nom" du backend.

Améliorer les performances de l'authentification

---

sv/static/sv/fichedetection_lieux_form.js
sv/tests/test_fichedetection_update.py

Problème:
Si je souhaite ajouter une commune sur un lieu existant, le champ Commune ne fonctionne pas. Pour reproduire le bug :
- Créer une fiche détection avec un lieu mais sans commune
- Allez sur le formulaire de modification de la fiche détection
- Ouvrir la modale correspond au lieu
- Le champ commune ne fonctionne pas

Corrige bug d'ajout commune dans un lieu existant

---

sv/tests/test_evenenement_visibilite_update.py

Nous avons eu un cas où deux structures avaient un nom similaire (Man et Woman), ce qui fait échouer le test (man étant "compris" dans woman on ne sait pas quel élément utiliser - `resolved to 2 elements`)

Fiabiliser les tests sur la visibilité

---

core/mixins.py
core/templates/core/_ouvrir_evenement_modal.html
core/urls.py
core/views.py
sv/templates/sv/evenement_detail.html
sv/tests/test_evenement_etats.py
sv/views.py

Ajout d'une action permettant de repasser l'évènement dans l'état EN_COURS. 
Seule l'AC peut effectuer cette action. 
Sa fin de suivi est aussi supprimé.

Pouvoir rouvrir un événement clôturé

---

.talismanrc
core/mixins.py
core/static/core/base.css
core/templates/core/_publier_and_notifier_ac_modal.html
core/templates/core/_publier_without_notifier_ac_modal.html
core/urls.py
core/views.py
sv/templates/sv/evenement_detail.html
sv/tests/test_evenement_details.py
sv/tests/test_evenement_etats.py

Cette PR permet de remplacer l'action de publier par deux actions : 
- Publier et déclarer à l’AC,
- Publier sans déclarer à l’AC.
Pour l'action "Publier sans déclarer à l’AC", une modale de confirmation est affichée puis l'événement est publié (passage à l'état `EN_COURS`).
Pour l'action "Publier et déclarer à l’AC" : 
- une modale est affichée,
- l'événement est publié (passage à l'état `EN_COURS`) et la notification à l'AC est envoyée. 
J'ai aussi : 
- ajouté deux mixins `WithPublishMixin` et `WithACNotificationMixin` pour factoriser le code utilisé dans plusieurs views (`PublishView`, `ACNotificationView`, `PublishAndACNotificationView`),
- deplacé les tests `test_can_publish_evenement` et `test_cant_forge_publication_of_evenement_we_are_not_owner` dans …

Modification actions de publication d'un évènement

---

ssa/static/ssa/_etablissement_form.js
ssa/tests/pages.py
ssa/tests/test_evenement_produit_creation.py

Corrige le scénario suivant:
- Créer un établissement
- Remplir le champ obligatoire
- Enregistrer la modale
- Editer
- Cliquer en dehors de la modale
- Editer à nouveau --> **Le formulaire est vide alors qu'on devrait avoir nos infos**
- explicitOriginalTarget ne fonctionne que sur firefox pas sur chrome
- sauvegarde du form pour pouvoir le réinitialiser si le changement est fait sans sauvegarde de la modale

Corriger les modales d'établissement dans SSA

---

core/static/core/siret.js
seves/settings.py
ssa/static/ssa/_etablissement_form.js
ssa/static/ssa/evenement_produit_form.css
ssa/templates/ssa/_etablissement_block.html
ssa/templates/ssa/evenement_produit_form.html
ssa/tests/pages.py
ssa/tests/test_api_views.py
ssa/tests/test_evenement_produit_creation.py
ssa/urls.py
ssa/views/__init__.py
ssa/views/api.py
ssa/views/produit.py
sv/static/sv/fichedetection_lieux_form.js

Dans SSA permettre de rechercher un établissement via son SIREN et de compléter le formulaire en utilisant les informations renvoyées par l'API.
Ajout d'une vue qui permet en plus d'obtenir le numéro d'agrément depuis le siret:
- Obligation de le faire côté back à cause de la politique CORS de l'hébergement des fichiers
- Version "naive" pour le moment, il est possible que la vue timeout et/ou que le champ mette du temps à se compléter au niveau frontend. Cette implémentation évite de devoir écrire un script de synchronisation des données des numéros d'agréement.
- J'ai réalisé des tests avec des numéros qui sont dans les derniers fichiers et c'est tout de même assez rapide.
Amélioration envisageable:
- Ajouter un retour UI pour indiquer que le numéro d'agrément est en train de se …

Permettre de chercher un établissement via SIREN

---

.talismanrc
core/constants.py
core/forms.py
core/managers.py
core/mixins.py
core/model_mixins.py
core/static/core/message_form.js
core/templates/core/_tableau_fil_de_suivi.html
core/views.py
ssa/forms.py
ssa/models/evenement_produit.py
ssa/tests/pages.py
ssa/tests/test_evenement_produit_details_performances.py
ssa/tests/test_evenement_produit_message.py
sv/forms.py
sv/models/evenements.py

Le but de ce commit est de pouvoir personaliser le comportement du message form en fonction de l'application visée. Au début du projet il était prévu que le comportement soit iso entre toutes les apps, mais il s'avère que non.
L'utilisation de l'héritage permet de personaliser le comportement (case a cocher pour SV, picker ChoiceJs pour SSA) tout en gardant 95% du comportement en commun.
- Changement du template de fil de suivi pour éviter d'avoir plusieurs élements avec le même ID
- Création des sous classes pour la personalisation et implémentation du nouveau comportement dans SSA

Permettre de personaliser le MessageForm

---

core/views.py
sv/tests/test_evenement_documents.py

Si j'ajoute un élément de suivi avec un document, et que j'essaie de modifier une information du document (nom du fichier, commentaire) via son formulaire de modification, une erreur 500 est générée (cf. erreur Sentry SEVES-4Q) : 
```python
AttributeError
'Message' object has no attribute 'is_draft'
```
Cela vient de la méthode `get_fiche_object` dans la view `DocumentUpdateView`. 
Cette méthode est censé renvoyer l'objet correspondant à l'évènement (`Evenement`) alors que l'objet renvoyé est de type `Message`.

Corrige bug modification document enregistré via un élement de suivi

---

sv/tests/test_fichedetection_create.py
sv/tests/test_utils.py

Avec l'agrandissement du contenu de la modale la case "est établissement" n'était plus trouvé. L'erreur ne remonte pas sur cette ligne à cause du force=True.
- Retrait du force=True pour avoir la vraie source du problème
- Utilisation du label pour le clic : évite d'essayer de cliquer sur la case et que l'événement soit intercepté.

Corriger un test sur SSA

---

.talismanrc
conftest.py
core/mixins.py
core/templates/core/_evenement_sort_link.html
ssa/templates/ssa/evenementproduit_list.html
ssa/tests/test_evenement_produit_list_order.py
ssa/views/produit.py
sv/managers.py
sv/templates/sv/evenement_list.html
sv/tests/test_evenement_list_order.py
sv/views.py

Cette PR ajoute la possibilité de pouvoir effectuer un tri (asc ou desc) pour chaque colonne des tableaux de liste d'évènements sauf pour : 
- commune (SV)
- Catégorie de produit (SSA)
- Catégorie de danger (SSA) 
J'ai factorisé la logique dans un nouveau mixin `WithOrderingMixin` (cf. app `core`).
J'ai utilisé un dictionnaire pour faire correspondre les valeurs des paramètres GET autorisés aux champs des modèles. Cela évite d'avoir le nom des champs directement dans les paramètres GET et d'avoir une liste des paramètres GET autorisés.
Ajout de tests pour SV et SSA.

Ajouter un tri sur les labels des listes d'évènements

---

ssa/forms.py

Retour utilisateur : le champ devrait rester vide tant que l’on n’a pas choisi une action

Retirer le choix par défaut sur les actions engagées

---

sv/templates/sv/evenement_detail.html
sv/tests/test_evenement_etats.py

Si l'agent connecté est de l'AC alors afficher qu'un bouton "Publier" pour la publication de l'évènement.

Modification libellé bouton publier événement si AC

---

ssa/templates/ssa/evenementproduit_list.html
ssa/tests/test_evenement_produit_list_order.py
ssa/views/produit.py

- Car cela n'a pas de sens d'un point de vue métier
- Car cela ne fonctionne pas, le filtre est implémenté sur la description alors que la description du tableau est un champ calculé `product_description`
De plus le nom du test est incorrect et parle d'organisme nuisible.

Retirer le tri sur la description dans SSA

---

ssa/models/evenement_produit.py

Pour que quand aucune valeur ne soit définie le template affiche "nc." comme pour les autres valeurs à la place de None.

Changer la valeur nulle de la quantification

---

ssa/models/etablissement.py
ssa/static/ssa/_etablissement_card.css
ssa/static/ssa/_etablissement_form.js

- Retirer l'icone pour être conforme à la maquette
- Changement de couleur pour éviter d'utiliser le rouge qui pourrait être synonyme de problème alors que c'est plutôt de l'ordre de l'information importante

Améliorer l'affichage de la position dans le dossier

---

core/pages.py
core/templates/core/_carte_resume_document.html
core/templates/core/_modale_edition_document.html
core/views.py
ssa/tests/test_evenement_produit_documents.py
sv/tests/test_evenement_documents.py

La redirection après l'édition d'un document dans SSA ne fonctionnait pas faute de paramètre next passé dans le template.
J'ai simplifié le code, car a priori on veut toujours ramener à la fiche après l'édition d'un document, nous n'avons donc plus besoin de ce paramètre.
Je commence a ajouter la notion de test "générique" pour les bloc commun, sur la base des pages on pourrait avoir une matrice de test commune pour plusieurs modèles.

Permettre d'éditer un document sur SSA

---

core/forms.py
core/static/core/message.css
core/static/core/message_form.js
sv/tests/test_evenement_message.py
sv/tests/test_evenement_performance_details.py

Ajout d'un lien permettant d'ajouter tous les contacts d'un événement lors de la rédaction d'un élément de suivi dans les destinataires ou copie.

Pouvoir ajouter tous les contacts d'un événement dans les destinaires d'un message

---

conftest.py
core/static/core/siret.js
ssa/forms.py
ssa/static/ssa/_etablissement_form.js
ssa/static/ssa/evenement_produit_form.css
ssa/templates/ssa/_etablissement_block.html
ssa/tests/pages.py
ssa/tests/test_evenement_produit_creation.py

Ce commit mélange des améliorations propres à SSA et des améliorations communes:
- Permet de passer un siret complet (ou un str de plus de 9 caractères) et de tout de même faire la recherche sur le SIREN.
- Le cas échéant ne montrer que le / les SIRET qui correspondent au terme recherché
- Permettre de forcer la valeur si la valeur saisi est complète
- Simplification de l'interface pour SSA (plus besoin de faire plusieurs clics).
- Afin que le champ choices JS avec la recherche soit toujours disponible sur la page de création d'événement produit on force un faux token via le JS dans la méthode navigate (pour éviter de devoir mocker cette partie à chaque fois).

Améliorer le comportement du bloc siret sur SSA

---

core/constants.py
sv/filters.py
sv/tests/test_evenement_search.py

Problème :
Le filtre “Région” se base sur la commune indiquée dans les lieux. Si aucune commune n’est ajoutée (comme le champ n’est pas obligatoire), alors la fiche ne sera pas remontée avec le filtre région.
Solution :
Ajouter un deuxième niveau dans le filtre “Région” : si la commune est vide dans la fiche, filtrer sur la région de la structure créatrice.
- ajout d'un mapping entre les régions (`nom)` et les structures (`niveau2`) concernées par SV,
- modification de la méthode `filter_region` pour prendre en compte sur le filtre sur la région de la structure créatrice,
- ajout d'un test.

Ajoute un deuxième niveau dans le filtre “Région” (formulaire de recherche d'évènements)

---

core/mixins.py
ssa/tests/test_evenement_produit_list_order.py
sv/tests/test_evenement_list_order.py

En cas d'égalité dans un tri (même nombre, même mot, etc.) trier par pk, surtout afin de rendre le code plus facilement testable.

Ajouter un ordre par défaut en cas d'égalité

---

sv/tests/test_fichezonedelimitee_detail.py

Empecher les surfaces et les rayons d'avoir exactement les mêmes valeurs et les mêmes unités, sinon on peut se retrouver dans la situation suivante:
```
playwright._impl._errors.Error: LocatorAssertions.to_be_visible: Error: strict mode violation: get_by_text("56 ha", exact=True) resolved to 2 elements:
E               1) <div class="fr-col">↵                                ↵               …</div> aka get_by_text("ha").nth(3)
E               2) <div class="fr-col">↵            ↵                56 ha↵            ↵…</div> aka get_by_text("ha").nth(4)
```

Fiabiliser un test sur le détail de la zone infestée

---

core/static/core/siret.js
ssa/tests/pages.py
ssa/tests/test_evenement_produit_creation.py
sv/tests/test_fichedetection_create.py

L'API utilisée ne renvoit par défaut que les 20 premiers résultats, ce commit augmente le seuil à 100 pour les cas où l'on tape un SIREN qui a plus de 20 établissements.
Exemple : en tapant 37861070300480 on recherche 378610703* qui contient 84 établissements.

Améliorer la recherche par SIRET/SIREN

---

core/tests/generic_tests/messages.py

Les tests utilisant la fonction `generic_test_can_finaliser_draft_note` cassent aléatoirement parce que le test essaie de vérifier l'existence d'un message trop vite après avoir POSTé la requête. Le test a été stabilisé avec une étape d'attente que la page affiche le message de succès avant d'effectuer les assertions du test.

Stabilisation des tests utilisant `generic_test_can_finaliser_draft_note`

---

ssa/static/ssa/_custom_tree_select.css

#1067 a réparé la taille des input treeselect par rapport aux autres champs purs DSFR mais il reste un décalage lorsque le dropdown est ouvert :
Après :

Fix sur la taille des input treeselect

---

sv/tests/test_evenement_details.py

Extrait d'un message explicatif:
On a eu un fail random sur _assert_fiche_zone_derniere_mise_a_jour_visible (via test_date_derniere_mise_a_jour_after_delete_detection_in_zone_infestee). Dans le helper, on vérifie que la date de dernière mise à jour de l'événement soit A et que la date de mise à jour de la zone soit aussi A (A = last_update_text dans le code). Pour autant on a la mise à jour de l'événement qui se a un endroit/moment dans le code et la mise à jour de la zone à un autre endroit/moment.
Il n'y a pas de garantie que cela soit la même valeur (la valeur n'est pas "passée") donc on peut avoir 13:39 dans un champ et 13:40 dans un autre.

Améliorer les tests sur la dernière date de mise à jour

---

core/pages.py
core/tests/generic_tests/contacts.py
core/views.py
ssa/tests/test_evenement_produit_contact_add.py
ssa/tests/test_evenement_produit_structure_add.py
sv/tests/test_evenement_contact_add.py
sv/tests/test_evenement_structure_add.py

Depuis d939ed2c31d39ed4bd15e80b8d40f19d79f2edbd l'ajout des structures et des agents ne fonctionne plus dans SSA car le modèle EvenementProduit n'a pas de notion de visilibité et donc n'utilise pas le mixin qui fourni la méthode `update_allowed_structures_and_visibility`.
Mise en commun d'un test minimal, a défaut de migrer tous les tests sous forme de tests génériques.
Fixes SEVES-57

Corriger l'ajout d'agent et de structures

---

core/static/core/ban_autocomplete.js
sv/static/sv/fichedetection_lieux_form.js

Annule les précédentes requêtes HTTP avant d'en relancer une ou de modifier le dropdown afin de ne pas le peupler avec des résultats qui pourraient être rendus obselètes par une interaction utilisateur/utilisatrice.
Cette PR n'ajoute pas de nouveaux tests car ce genre de situations avec évènements concurrents est très difficile à tester de façon fiable pour peu de valeur ajoutée.

fix: recherche communes — empêche le peuplement de résultats périmés

---

conftest.py

Pour une raison que j'ignore encore le mode debug rend le démarrage d'un serveur Django extrêmement lent ici. Du coup Playwright timeout avant même que Django ai eu le temps de recevoir la moindre requête HTTP. Cette fonctionnalité me rend beaucoup plus simple de debugger ces tests.

feat(tests): Permet de configurer le timeout global de Playwright avec une variable d'env

---

.github/workflows/django.yml
.talismanrc
conftest.py
requirements.in
requirements.txt

- Cache les dépendances Playwright
- Relance les tests en échec une seule fois après un délai de 10s secondes sur un `ERR_NETWORK_CHANGED`
- Augmente le nombre de tests en parallèle de 8 à 12.

Améliorations sur la CI

---

ssa/static/ssa/evenement_produit_form.js

Afin d'éviter qu'ils s'ouvrent vert le haut et soient tronqués par le bloc parent.

Toujours ouvrir les pickers treeselectjs vers le bas

---

core/static/core/base.css
seves/context_processors.py

Les animations d'interface posent un vrai défi aux tests d'intégration au point qu'il est de notoriété publique dans la commun du développement Android qu'il vaut mieux les désactiver entièrement. Cette PR tente de supprimer au maximum les animations CSS sur l'interface pendant les tests pour éviter les problèmes de tests flaky à cause des collisions dopération dûes à des animations.

feat(test): désactive toutes les animations CSS pendant les tests

---

ssa/forms.py
ssa/tests/pages.py
ssa/tests/test_evenement_produit_creation.py
ssa/tests/test_evenement_produit_update.py

Pour rester cohérent avec la contrainte de base on vide la valeur du champ PAM quand le danger est non bactérien (le champ est déjà masqué côté front).

Vider le champ PAM à la mise a jour si danger non bactérien

---

ssa/forms.py
ssa/formsets.py
ssa/static/ssa/_etablissement_form.js
ssa/static/ssa/_rappel_conso_form.js
ssa/templates/ssa/_etablissement_block.html
ssa/templates/ssa/_etablissement_modal.html
ssa/tests/conftest.py
ssa/tests/pages.py
ssa/tests/test_evenement_produit_creation.py
ssa/tests/test_evenement_produit_details.py
ssa/tests/test_evenement_produit_update.py
ssa/views/produit.py

Permettre d'éditer les établissements déjà existant lors de la mise à jour d'une fiche événement produit:
- Ajout d'un utilitaire de test pour vérifier qu'une carte établissement est correcte

Permettre d'éditer les établissements

---

ssa/tests/test_evenement_produit_update.py

Pour les événements publiés (qui n'ont pas de bouton de sauvegarde en brouillon), corrige la sauvegarde des numéros de rappels conso.

Corriger les numéros de rappels conso sur Evenement publié

---

core/static/core/base.css
core/static/core/contact_add_form.js

La librairie Choices apporte son propre design de chevron qui entre en conflit avec celui de la DSFR. Cette PR corrige le CSS pour que les champs de Choice suivent le design du DSFR.

Améliorations CSS sur le champs qui utilise le composant Choices

---

core/factories.py
core/forms.py
core/managers.py
core/tests/generic_tests/messages.py
ssa/forms.py
sv/forms.py

Cette PR permet de ne pas proposer à des destinataires qui n'ont pas accès à l'application (SSA/SV) à partir de laquelle l'utilisateur ou l'utilisatrice envoie des messages.
Il manque encore des tests pour cette fonctionnalité spécifique.

Permettre de filtrer les destinataires des messages par application

---

conftest.py
ssa/tests/conftest.py
sv/tests/test_evenement_search.py

Toujours le même soucis quand on travaille avec les modèles `Region` et `Departement` pour lesquels on n'a jamais de garantie, quand le test s'exécute, que les enregistrements existent en BDD. La fixture `ensure_departements` a été rajoutée pour s'en assurer.

Fix de la fragilité sur le test `test_search_with_region`

---

ssa/models/evenement_produit.py
ssa/tests/test_evenement_produit_export.py
ssa/tests/test_evenement_produit_list.py
tiac/models.py

To be able to make the difference between the fiche A (Alim, SSA) and T (TIAC, SSA).

Add prefix to object number in interface

---

core/forms.py
core/tests/generic_tests/documents.py
core/tests/generic_tests/messages.py
tiac/tests/test_evenement_simple_creation.py

This was not the case anymore since the different apps have different allowed document types.

Add default choice on document type

---

.talismanrc
core/mixins.py

When the INSEE api is in maintenance we don't receive a valide JSON from the API, causing a few important pages not to load.

Allow to use app even when INSEE is down

---

ssa/templates/ssa/base.html
sv/templates/sv/base.html
tiac/templates/tiac/base.html

Je vient de tomber là-dessus. Je suis pas sûr de comprendre la raison pour laquelle le lien est contenu dans un bouton sur lequel n'est associé aucun listener d'évènement. Ça me semble sémantiquement erroné.

Nettoyage du HTML sur les boutons de création évènement/fiche pour TIAC/SSA/SV

---

sv/tests/test_fichedetection_create.py

Initial error:
>       region = Region.objects.create(nom="Île-de-France")
FAILED sv/tests/test_fichedetection_create.py::test_can_add_lieu_with_adresse_etablissement_autocomplete - django.db.utils.IntegrityError: duplicate key value violates unique constraint "sv_region_nom_key"
DETAIL:  Key (nom)=(Île-de-France) already exists.

Make sure a test wont fail randomly

---

tiac/static/tiac/base.css

Keep them only in the etablissement modal in TIAC for now.

Remove second * character in transfer modal

---

sv/static/sv/fichedetection_form.css
sv/static/sv/fichedetection_lieux_form.js

Les autres utilisations sont esthétiques donc ça pose moins de problème.

Réparation sur le formulaire établissement pour les navigateur qui n'implémentent pas le sélecteur ':has()'

---

tiac/templates/tiac/investigation.html

Make sure the markup is consistent for TIAC creation
